// Unit tests for export.cpp — `ezmk project export cmake` (CMakeLists.txt).
#define CATCH_AMALGAMATED_CUSTOM_MAIN
#include "catch2.hpp"
#include "test_helpers.hpp"
#include "ezmk/export.hpp"
#include "ezmk/config.hpp"
#include "ezmk/toolchain.hpp"
#include "ezmk/util.hpp"
#include "nlohmann_json.hpp"

#include <filesystem>
#include <fstream>
#include <string>

namespace fs = std::filesystem;
using namespace ezmk::config;
using namespace ezmk::export_gen;

namespace {

// Minimal executable project config.
EzConfig make_exe_config() {
    EzConfig cfg;
    cfg.project.name = "demo";
    cfg.project.type = "executable";
    cfg.project.version = "1.2.0";
    cfg.project.language = "C++17";
    cfg.compile.flags = {"-Wall", "-O2"};
    cfg.compile.include_dirs = {"include"};
    cfg.compile.src_dirs = {"src"};
    return cfg;
}

} // namespace

// ===================================================================
// Header / project-level mapping
// ===================================================================

TEST_CASE("export cmake: header + project() + add_executable", "[export]") {
    auto cfg = make_exe_config();
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("cmake_minimum_required(VERSION 3.16)") != std::string::npos);
    REQUIRE(t.find("Generated by `ezmk project export cmake`") != std::string::npos);
    REQUIRE(t.find("project(demo VERSION 1.2.0 LANGUAGES CXX)") != std::string::npos);
    REQUIRE(t.find("add_executable(demo ${demo_SOURCES})") != std::string::npos);
}

TEST_CASE("export cmake: static/shared library types", "[export]") {
    auto cfg = make_exe_config();
    cfg.project.type = "static";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("add_library(demo STATIC ${demo_SOURCES})") != std::string::npos);

    cfg.project.type = "shared";
    t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("add_library(demo SHARED ${demo_SOURCES})") != std::string::npos);
}

TEST_CASE("export cmake: utils type → WARNING, no target", "[export]") {
    auto cfg = make_exe_config();
    cfg.project.type = "utils";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("message(WARNING \"project type 'utils'") != std::string::npos);
    REQUIRE(t.find("add_executable") == std::string::npos);
    REQUIRE(t.find("add_library") == std::string::npos);
}

TEST_CASE("export cmake: header_only → INTERFACE", "[export]") {
    auto cfg = make_exe_config();
    cfg.project.header_only = true;
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("add_library(demo INTERFACE)") != std::string::npos);
}

TEST_CASE("export cmake: precompiled → IMPORTED", "[export]") {
    auto cfg = make_exe_config();
    cfg.project.precompiled = true;
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("add_library(demo IMPORTED)") != std::string::npos);
    REQUIRE(t.find("lib/libdemo.a") != std::string::npos);
}

// 1.2.0-dev.11: CMake project() VERSION only accepts numeric dotted versions —
// a pre-release like "1.2.0-dev.10" must not break the generated file.
TEST_CASE("export cmake: non-numeric version omits VERSION (dev.11)", "[export][1.2.0-dev.11]") {
    auto cfg = make_exe_config();
    cfg.project.version = "1.2.0-dev.10";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    CHECK(t.find("VERSION 1.2.0-dev.10") == std::string::npos);
    CHECK(t.find("VERSION omitted") != std::string::npos);
    CHECK(t.find("project(demo") != std::string::npos);   // project() itself intact
}

// 1.2.0-dev.11: precompiled export resolves the actual archive via the shared
// selector (os-arch[-compiler][-abi] naming) instead of a hardcoded lib<name>.a.
TEST_CASE("export cmake: precompiled reuses the archive selector (dev.11)", "[export][1.2.0-dev.11]") {
    TempDir tmp;
    auto cfg = make_exe_config();
    cfg.project.name = "pre";
    cfg.project.type = "static";
    cfg.project.precompiled = true;
    fs::create_directories(tmp.path / "lib");
    // Only a toolchain-tagged archive (L3: same compiler, no abi segment).
    std::string plat = ezmk::util::detect_platform_tag();
    auto tc = ezmk::toolchain::detect_toolchain();
    std::string comp = ezmk::toolchain::compiler_tag(tc);
    REQUIRE_FALSE(comp.empty());
    std::string tag = plat + "-" + comp;
    { std::ofstream(tmp.path / "lib" / ("libpre." + tag + ".a")) << "x"; }

    auto t = build_cmake_text(cfg, tmp.path, ExportOptions{});
    CHECK(t.find("libpre." + tag + ".a") != std::string::npos);
    CHECK(t.find("libpre.a\"") == std::string::npos);  // not the hardcoded fallback
}

TEST_CASE("export cmake: C project → LANGUAGES C + *.c glob + C_STANDARD", "[export]") {
    auto cfg = make_exe_config();
    cfg.project.language = "C11";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("LANGUAGES C)") != std::string::npos);
    REQUIRE(t.find("${CMAKE_CURRENT_SOURCE_DIR}/src/*.c") != std::string::npos);
}

// 1.3.1: range languages export the MIN standard — the old bare digit
// extraction produced "CXX_STANDARD 1117" for "C++11..C++17" (坑 1).
TEST_CASE("export cmake: range language exports min standard (1.3.1)", "[export][1.3.1]") {
    auto cfg = make_exe_config();
    cfg.project.language = "C++11..C++17";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("CXX_STANDARD 11") != std::string::npos);
    REQUIRE(t.find("CXX_STANDARD 1117") == std::string::npos);
}

TEST_CASE("export cmake: >= range exports min standard (1.3.1)", "[export][1.3.1]") {
    auto cfg = make_exe_config();
    cfg.project.language = ">=C++11";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("CXX_STANDARD 11") != std::string::npos);
    REQUIRE(t.find("CXX_STANDARD 1117") == std::string::npos);
}

TEST_CASE("export cmake: exact language export unchanged (1.3.1)", "[export][1.3.1]") {
    auto cfg = make_exe_config();
    cfg.project.language = "C++17";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("CXX_STANDARD 17") != std::string::npos);
}

// ===================================================================
// Compile mapping
// ===================================================================

TEST_CASE("export cmake: source glob default", "[export]") {
    auto cfg = make_exe_config();
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("file(GLOB_RECURSE demo_SOURCES CONFIGURE_DEPENDS") != std::string::npos);
    REQUIRE(t.find("${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp") != std::string::npos);
}

TEST_CASE("export cmake: --no-glob emits explicit source list", "[export]") {
    TempDir tmp;
    fs::create_directories(tmp.path / "src");
    { std::ofstream(tmp.path / "src" / "main.cpp") << "int main(){}\n"; }
    auto cfg = make_exe_config();
    ExportOptions opts;
    opts.use_glob = false;
    auto t = build_cmake_text(cfg, tmp.path, opts);
    REQUIRE(t.find("set(demo_SOURCES") != std::string::npos);
    REQUIRE(t.find("file(GLOB_RECURSE") == std::string::npos);
    REQUIRE(t.find("main.cpp") != std::string::npos);
}

TEST_CASE("export cmake: flags split — -std/-D/-I extracted, macros + ezmk_macros", "[export]") {
    auto cfg = make_exe_config();
    cfg.compile.flags = {"-Wall", "-std=c++17", "-DEZMK_EXTRA=1", "-Iextra_inc"};
    cfg.compile.macros = {{"DEBUG", "0"}, {"APP_NAME", "demo"}};
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    // -std → CXX_STANDARD; GNU off for plain -std=c++17.
    REQUIRE(t.find("CXX_STANDARD 17") != std::string::npos);
    REQUIRE(t.find("CXX_EXTENSIONS OFF") != std::string::npos);
    // -D from flags + [compile].macros + ezmk macros all land in definitions.
    REQUIRE(t.find("EZMK_EXTRA=1") != std::string::npos);
    REQUIRE(t.find("DEBUG=0") != std::string::npos);
    REQUIRE(t.find("APP_NAME=\"demo\"") != std::string::npos);
    REQUIRE(t.find("EZMK=1") != std::string::npos);
    // Plain flag stays in compile_options.
    REQUIRE(t.find("-Wall") != std::string::npos);
    // Split flags no longer appear verbatim.
    REQUIRE(t.find("-std=c++17") == std::string::npos);
    REQUIRE(t.find("-DEZMK_EXTRA=1") == std::string::npos);
    REQUIRE(t.find("-Iextra_inc") == std::string::npos);
}

TEST_CASE("export cmake: msvc_flags wrapped in genex", "[export]") {
    auto cfg = make_exe_config();
    cfg.compile.msvc_flags = {"/W4"};
    cfg.link.msvc_flags = {"/LTCG"};
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("COMPILE_LANG_AND_ID:CXX,MSVC") != std::string::npos);
    REQUIRE(t.find("/W4") != std::string::npos);
    REQUIRE(t.find("/LTCG") != std::string::npos);
}

TEST_CASE("export cmake: external include dir stays absolute + comment", "[export]") {
    CwdGuard guard;
    fs::path proj = fs::current_path();
    fs::path external = fs::temp_directory_path() / "ezmk_outside_inc_xyz";
    auto cfg = make_exe_config();
    cfg.compile.include_dirs = {"include", external.string()};
    auto t = build_cmake_text(cfg, proj, ExportOptions{});
    REQUIRE(t.find("outside the project root") != std::string::npos);
    REQUIRE(t.find(external.generic_string()) != std::string::npos);
}

// ===================================================================
// Link mapping
// ===================================================================

TEST_CASE("export cmake: link mapping — system_targets + -l/-L split", "[export]") {
    auto cfg = make_exe_config();
    cfg.link.system_targets = {"dl"};
    cfg.link.flags = {"-lpthread", "-Lextra_lib", "-s"};
    cfg.link.link_dirs = {"mylib"};
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("target_link_libraries(demo PRIVATE dl pthread)") != std::string::npos);
    REQUIRE(t.find("target_link_directories(demo PRIVATE") != std::string::npos);
    REQUIRE(t.find("target_link_options(demo PRIVATE -s)") != std::string::npos);
}

// ===================================================================
// Dependencies
// ===================================================================

TEST_CASE("export cmake: portable dep → find_package", "[export]") {
    auto cfg = make_exe_config();
    cfg.depends.libs.push_back({"openssl", {}});
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("find_package(OpenSSL QUIET)") != std::string::npos);
    REQUIRE(t.find("if(TARGET OpenSSL::SSL)") != std::string::npos);
}

TEST_CASE("export cmake: unaliased dep → upper-cased find_package placeholder", "[export]") {
    auto cfg = make_exe_config();
    cfg.depends.libs.push_back({"myweirdlib", {}});
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("find_package(MYWEIRDLIB QUIET)") != std::string::npos);
    REQUIRE(t.find("add manually") != std::string::npos);
}

TEST_CASE("export cmake: --resolve emits installed dep paths", "[export]") {
    CwdGuard guard;
    fs::path proj = fs::current_path();
    fs::create_directories(proj / ".ezmk" / "pkg" / "fmt" / "include");
    fs::create_directories(proj / ".ezmk" / "pkg" / "fmt" / "lib");
    { std::ofstream(proj / ".ezmk" / "pkg" / "fmt" / "include" / "fmt.hpp") << "x\n"; }
    { std::ofstream(proj / ".ezmk" / "pkg" / "fmt" / "lib" / "libfmt.a") << "x\n"; }

    auto cfg = make_exe_config();
    cfg.depends.libs.push_back({"fmt", {}});
    ExportOptions opts;
    opts.resolve = true;
    auto t = build_cmake_text(cfg, proj, opts);
    REQUIRE(t.find("resolved from installed package") != std::string::npos);
    REQUIRE(t.find(".ezmk/pkg/fmt/include") != std::string::npos);
    REQUIRE(t.find("libfmt.a") != std::string::npos);
}

// ===================================================================
// Hooks
// ===================================================================

TEST_CASE("export cmake: hooks → find_program + add_custom_command PRE/POST", "[export]") {
    auto cfg = make_exe_config();
    cfg.hooks.pre_build = "scripts/pre.lua";
    cfg.hooks.post_build = "scripts/post.lua";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    // dev.8: hooks run via the standalone ezmk-lua runtime.
    REQUIRE(t.find("find_program(EZMK_LUA ezmk-lua)") != std::string::npos);
    REQUIRE(t.find("if(NOT EZMK_LUA)") != std::string::npos);
    REQUIRE(t.find("message(WARNING \"[hooks] need 'ezmk-lua' on PATH") != std::string::npos);
    // pre_build → PRE_BUILD, post_build → POST_BUILD; script path rooted at the
    // CMake source dir; ctx injected via --project-root / --output.
    REQUIRE(t.find("add_custom_command(TARGET demo PRE_BUILD") != std::string::npos);
    REQUIRE(t.find("COMMAND ${EZMK_LUA} \"${CMAKE_CURRENT_SOURCE_DIR}/scripts/pre.lua\"")
            != std::string::npos);
    REQUIRE(t.find("--project-root ${CMAKE_CURRENT_SOURCE_DIR}") != std::string::npos);
    REQUIRE(t.find("--output $<TARGET_FILE:demo>") != std::string::npos);
    REQUIRE(t.find("add_custom_command(TARGET demo POST_BUILD") != std::string::npos);
    REQUIRE(t.find("\"${CMAKE_CURRENT_SOURCE_DIR}/scripts/post.lua\"") != std::string::npos);
    // The old "not exported" blanket warning must be gone.
    REQUIRE(t.find("NOT exported") == std::string::npos);
}

TEST_CASE("export cmake: on_failure stays a comment (no CMake failure hook)", "[export]") {
    auto cfg = make_exe_config();
    cfg.hooks.on_failure = "scripts/fail.lua";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    // No pre/post hooks → no find_program / add_custom_command block at all.
    REQUIRE(t.find("find_program(EZMK_LUA") == std::string::npos);
    REQUIRE(t.find("add_custom_command") == std::string::npos);
    REQUIRE(t.find("on_failure \"scripts/fail.lua\"") != std::string::npos);
    REQUIRE(t.find("not exported") != std::string::npos);
}

TEST_CASE("export cmake: hook command inlines --profile", "[export]") {
    auto cfg = make_exe_config();
    cfg.hooks.post_build = "scripts/post.lua";
    cfg.compile_profiles["release"] = ProfileConfig{{}, {}, {}};
    ExportOptions opts;
    opts.profile = "release";
    auto t = build_cmake_text(cfg, fs::current_path(), opts);
    REQUIRE(t.find("--profile release") != std::string::npos);
}

TEST_CASE("export cmake: no hooks → no hooks section", "[export]") {
    auto cfg = make_exe_config();
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("[hooks]") == std::string::npos);
    REQUIRE(t.find("ezmk-lua") == std::string::npos);
}

// ===================================================================
// --profile
// ===================================================================

TEST_CASE("export cmake: --profile applies profile flags/macros", "[export]") {
    auto cfg = make_exe_config();
    cfg.compile_profiles["debug"] = ProfileConfig{{"-g"}, {}, {{"DEBUG", "1"}}};
    ExportOptions opts;
    opts.profile = "debug";
    auto t = build_cmake_text(cfg, fs::current_path(), opts);
    REQUIRE(t.find("-g") != std::string::npos);
    REQUIRE(t.find("DEBUG=1") != std::string::npos);
}

// ===================================================================
// Overwrite safety (export_cmake writes to disk)
// ===================================================================

TEST_CASE("export cmake: refuses overwrite without --overwrite", "[export]") {
    TempDir tmp;
    auto cfg = make_exe_config();
    { std::ofstream(tmp.path / "CMakeLists.txt") << "old\n"; }
    REQUIRE_THROWS_AS(export_cmake(cfg, tmp.path, ExportOptions{}), ezmk::fatal_error);
}

TEST_CASE("export cmake: --overwrite replaces existing file", "[export]") {
    TempDir tmp;
    auto cfg = make_exe_config();
    { std::ofstream(tmp.path / "CMakeLists.txt") << "old\n"; }
    ExportOptions opts;
    opts.overwrite = true;
    REQUIRE_NOTHROW(export_cmake(cfg, tmp.path, opts));
    auto content = ezmk::util::file_read(tmp.path / "CMakeLists.txt");
    REQUIRE(content.find("cmake_minimum_required") != std::string::npos);
}

// ===================================================================
// 1.4.0-dev.1 — project export vscode (debug config trio)
// ===================================================================

using ezmk::toolchain::CompilerFamily;

// ---- per-platform debugger table (design §3.2) ----

TEST_CASE("export vscode: debugger table — Windows+MSVC → cppvsdbg .exe", "[export][1.4.0-dev.1]") {
    auto d = select_vscode_debugger(HostPlatform::Windows, CompilerFamily::Msvc, "demo");
    REQUIRE(d.type == "cppvsdbg");
    REQUIRE(d.mi_debugger_path.empty());
    REQUIRE(d.program == "build/demo.exe");
}

TEST_CASE("export vscode: debugger table — Linux+GCC → cppdbg+gdb", "[export][1.4.0-dev.1]") {
    auto d = select_vscode_debugger(HostPlatform::Linux, CompilerFamily::Gcc, "demo");
    REQUIRE(d.type == "cppdbg");
    REQUIRE(d.mi_debugger_path == "gdb");
    REQUIRE(d.program == "build/demo");
}

TEST_CASE("export vscode: debugger table — Linux+Clang → cppdbg+lldb", "[export][1.4.0-dev.1]") {
    auto d = select_vscode_debugger(HostPlatform::Linux, CompilerFamily::Clang, "demo");
    REQUIRE(d.type == "cppdbg");
    REQUIRE(d.mi_debugger_path == "lldb");
    REQUIRE(d.program == "build/demo");
}

TEST_CASE("export vscode: debugger table — macOS+Clang → lldb", "[export][1.4.0-dev.1]") {
    auto d = select_vscode_debugger(HostPlatform::MacOs, CompilerFamily::Clang, "demo");
    REQUIRE(d.type == "lldb");
    REQUIRE(d.mi_debugger_path.empty());
    REQUIRE(d.program == "build/demo");
}

TEST_CASE("export vscode: debugger table — Windows+GCC → cppdbg+gdb .exe", "[export][1.4.0-dev.1]") {
    auto d = select_vscode_debugger(HostPlatform::Windows, CompilerFamily::Gcc, "demo");
    REQUIRE(d.type == "cppdbg");
    REQUIRE(d.mi_debugger_path == "gdb");
    REQUIRE(d.program == "build/demo.exe");
}

// ---- launch.json ----

TEST_CASE("export vscode: launch.json key fields", "[export][1.4.0-dev.1]") {
    auto cfg = make_exe_config();
    auto files = build_vscode_files(cfg, fs::current_path(), ExportOptions{});
    auto launch = nlohmann::json::parse(files.launch);   // must be valid JSON
    REQUIRE(launch["version"] == "0.2.0");
    REQUIRE(launch["configurations"].is_array());
    REQUIRE(launch["configurations"].size() == 1);
    auto& c = launch["configurations"][0];
    REQUIRE(c["request"] == "launch");
    REQUIRE(c["preLaunchTask"] == "ezmk-build");
    REQUIRE(c["cwd"] == "${workspaceFolder}");
    REQUIRE(c["externalConsole"] == false);
    // program → ${workspaceFolder}/build/<name>[.exe]
    std::string prog = c["program"];
    REQUIRE(prog.rfind("${workspaceFolder}/build/demo", 0) == 0);
    // type matches the current platform + detected toolchain
    auto tc = ezmk::toolchain::detect_toolchain();
    auto dbg = select_vscode_debugger(current_host_platform(), tc.family, "demo");
    REQUIRE(c["type"] == dbg.type);
    if (dbg.type == "cppdbg") {
        REQUIRE(c["miDebuggerPath"] == dbg.mi_debugger_path);
        REQUIRE(c["setupCommands"].is_array());
        REQUIRE(c["setupCommands"][0]["text"] == "-enable-pretty-printing");
    }
}

// ---- tasks.json ----

TEST_CASE("export vscode: tasks.json key fields + no args without profile", "[export][1.4.0-dev.1]") {
    auto cfg = make_exe_config();
    auto files = build_vscode_files(cfg, fs::current_path(), ExportOptions{});
    auto tasks = nlohmann::json::parse(files.tasks);    // must be valid JSON
    REQUIRE(tasks["version"] == "2.0.0");
    REQUIRE(tasks["tasks"].size() == 1);
    auto& t = tasks["tasks"][0];
    REQUIRE(t["label"] == "ezmk-build");                // cross-ref with launch
    REQUIRE(t["type"] == "shell");
    REQUIRE(t["command"] == "ezmk build");
    REQUIRE(t.contains("args") == false);               // no --profile → no args
    REQUIRE(t["group"]["kind"] == "build");
    REQUIRE(t["group"]["isDefault"] == true);
}

TEST_CASE("export vscode: tasks.json --profile injects args", "[export][1.4.0-dev.1]") {
    auto cfg = make_exe_config();
    cfg.compile_profiles["debug"] = ProfileConfig{{"-g"}, {}, {{"DEBUG", "1"}}};
    ExportOptions opts;
    opts.profile = "debug";
    auto files = build_vscode_files(cfg, fs::current_path(), opts);
    auto tasks = nlohmann::json::parse(files.tasks);
    REQUIRE(tasks["tasks"][0]["args"] ==
            nlohmann::json::array({"--profile", "debug"}));
}

TEST_CASE("export vscode: unknown profile is fatal", "[export][1.4.0-dev.1]") {
    auto cfg = make_exe_config();
    ExportOptions opts;
    opts.profile = "nope";
    REQUIRE_THROWS_AS(build_vscode_files(cfg, fs::current_path(), opts),
                      ezmk::fatal_error);
}

// ---- settings.json ----

TEST_CASE("export vscode: settings prefers compile_commands", "[export][1.4.0-dev.1]") {
    TempDir tmp;
    auto cfg = make_exe_config();
    cfg.compile.compile_commands = true;
    auto files = build_vscode_files(cfg, tmp.path, ExportOptions{});
    auto settings = nlohmann::json::parse(files.settings);  // must be valid JSON
    REQUIRE(settings["clangd.arguments"] ==
            nlohmann::json::array({"--compile-commands-dir=${workspaceFolder}"}));
    REQUIRE(settings.contains("C_Cpp.default.includePath") == false);
    REQUIRE(settings.contains("C_Cpp.default.defines") == false);
}

TEST_CASE("export vscode: settings falls back to C_Cpp without a db", "[export][1.4.0-dev.1]") {
    TempDir tmp;
    auto cfg = make_exe_config();
    cfg.compile.flags = {"-Wall", "-Iextra", "-DEXTRA=1"};
    cfg.compile.macros = {{"DEBUG", "1"}};
    auto files = build_vscode_files(cfg, tmp.path, ExportOptions{});
    auto settings = nlohmann::json::parse(files.settings);
    REQUIRE(settings.contains("clangd.arguments") == false);
    // includePath: resolved absolute — <tmp>/include (default) + <tmp>/extra
    bool found_include = false, found_extra = false;
    for (auto& p : settings["C_Cpp.default.includePath"]) {
        std::string s = p;
        if (s == (tmp.path / "include").lexically_normal().generic_string())
            found_include = true;
        if (s == (tmp.path / "extra").lexically_normal().generic_string())
            found_extra = true;
        REQUIRE(fs::path(s).is_absolute());
    }
    REQUIRE(found_include);
    REQUIRE(found_extra);
    // defines: -D flags + [compile].macros + ezmk standard macros
    bool has_extra = false, has_debug = false, has_ezmk = false;
    for (auto& d : settings["C_Cpp.default.defines"]) {
        std::string s = d;
        if (s == "EXTRA=1") has_extra = true;
        if (s == "DEBUG=1") has_debug = true;
        if (s == "EZMK=1") has_ezmk = true;
    }
    REQUIRE(has_extra);
    REQUIRE(has_debug);
    REQUIRE(has_ezmk);
}

TEST_CASE("export vscode: settings fallback includes installed dep dirs", "[export][1.4.0-dev.1]") {
    CwdGuard guard;
    fs::path proj = fs::current_path();
    fs::create_directories(proj / ".ezmk" / "pkg" / "fmt" / "include");
    { std::ofstream(proj / ".ezmk" / "pkg" / "fmt" / "include" / "fmt.hpp") << "x\n"; }

    auto cfg = make_exe_config();
    cfg.depends.libs.push_back({"fmt", {}});
    auto files = build_vscode_files(cfg, proj, ExportOptions{});
    auto settings = nlohmann::json::parse(files.settings);
    bool found = false;
    for (auto& p : settings["C_Cpp.default.includePath"]) {
        std::string s = p;
        if (s.find(".ezmk/pkg/fmt/include") != std::string::npos) found = true;
    }
    REQUIRE(found);
}

// ---- overwrite protection (export_vscode writes to disk) ----

TEST_CASE("export vscode: refuses overwrite without --overwrite", "[export][1.4.0-dev.1]") {
    TempDir tmp;
    fs::create_directories(tmp.path / ".vscode");
    { std::ofstream(tmp.path / ".vscode" / "launch.json") << "old\n"; }
    auto cfg = make_exe_config();
    REQUIRE_THROWS_AS(export_vscode(cfg, tmp.path, ExportOptions{}),
                      ezmk::fatal_error);
}

TEST_CASE("export vscode: --overwrite writes the full trio", "[export][1.4.0-dev.1]") {
    TempDir tmp;
    fs::create_directories(tmp.path / ".vscode");
    { std::ofstream(tmp.path / ".vscode" / "launch.json") << "old\n"; }
    auto cfg = make_exe_config();
    ExportOptions opts;
    opts.overwrite = true;
    REQUIRE_NOTHROW(export_vscode(cfg, tmp.path, opts));
    for (const char* name : {"launch.json", "tasks.json", "settings.json"}) {
        REQUIRE(ezmk::util::file_exists(tmp.path / ".vscode" / name));
    }
    auto launch = ezmk::util::file_read(tmp.path / ".vscode" / "launch.json");
    REQUIRE(launch.find("\"version\"") != std::string::npos);
    auto tasks = ezmk::util::file_read(tmp.path / ".vscode" / "tasks.json");
    REQUIRE(tasks.find("ezmk-build") != std::string::npos);
    auto settings = ezmk::util::file_read(tmp.path / ".vscode" / "settings.json");
    REQUIRE(settings.find("C_Cpp.default.includePath") != std::string::npos);
}
