// Unit tests for the embedded example table (1.2.3).
// Verifies the build-time embedded table (src/example_data.cpp, generated by
// scripts/embed_examples.py) matches the examples/ source tree exactly — the
// anti-drift guard for the "single source of truth" design.
#define CATCH_AMALGAMATED_CUSTOM_MAIN
#include "catch2.hpp"
#include "ezmk/example.hpp"
#include "ezmk/util.hpp"

#include <algorithm>
#include <filesystem>
#include <set>
#include <string>
#include <vector>

namespace fs = std::filesystem;
using namespace ezmk::example;

namespace {

// Find the repo root (the directory containing examples/) by walking up.
fs::path find_examples_dir() {
    fs::path cwd = fs::current_path();
    while (!cwd.empty() && cwd != cwd.root_path()) {
        if (fs::exists(cwd / "examples") && fs::is_directory(cwd / "examples")) {
            return cwd / "examples";
        }
        cwd = cwd.parent_path();
    }
    return {};
}

// All scaffolded files under an example dir, as forward-slash relative paths
// (excluding description.txt — metadata, not generated content, and the
// generated build/.ezmk dirs + binary artifacts — matching embed_examples.py,
// so the embedded table and the source tree are compared on the same set).
std::set<std::string> list_files(const fs::path& dir) {
    std::set<std::string> files;
    for (auto& e : fs::recursive_directory_iterator(dir)) {
        if (e.is_regular_file()) {
            auto rel = fs::relative(e.path(), dir).generic_string();
            if (rel == "description.txt") continue;
            auto first = rel.substr(0, rel.find('/'));
            if (first == "build" || first == ".ezmk" || first == ".git") continue;
            auto ext = e.path().extension().string();
            if (ext == ".exe" || ext == ".o" || ext == ".obj" || ext == ".a" ||
                ext == ".lib" || ext == ".dll" || ext == ".so" || ext == ".dylib" ||
                ext == ".zst" || ext == ".tar" || ext == ".gz" || ext == ".zip")
                continue;
            files.insert(rel);
        }
    }
    return files;
}

} // namespace

TEST_CASE("example: embedded table is non-empty", "[example][1.2.3]") {
    REQUIRE_FALSE(embedded_examples().empty());
}

TEST_CASE("example: embedded table matches examples/ source tree", "[example][1.2.3]") {
    fs::path ex = find_examples_dir();
    if (ex.empty()) {
        SKIP("examples/ directory not found — run tests from the repo root");
    }

    const auto& embedded = embedded_examples();

    // Disk example dirs (skip README.md and description.txt).
    std::set<std::string> disk_names;
    for (auto& e : fs::directory_iterator(ex)) {
        if (e.is_directory()) disk_names.insert(e.path().filename().string());
    }

    // Every disk example is embedded, with a non-empty description.
    for (auto& name : disk_names) {
        auto it = std::find_if(embedded.begin(), embedded.end(),
                               [&](const Example& exm) { return name == exm.name; });
        INFO("embedded table must contain: " << name);
        REQUIRE(it != embedded.end());
        REQUIRE(std::string(it->description).size() > 0);
    }

    // No extra entries in the embedded table.
    REQUIRE(embedded.size() == disk_names.size());

    // Per example: file set + content must match the source tree exactly.
    for (auto& exm : embedded) {
        auto disk_files = list_files(ex / exm.name);
        std::set<std::string> emb_files;
        for (auto& f : exm.files) emb_files.insert(f.path);
        INFO("file set for: " << exm.name);
        REQUIRE(emb_files == disk_files);

        for (auto& f : exm.files) {
            auto content = ezmk::util::file_read(ex / exm.name / f.path);
            INFO("content drift for: " << exm.name << "/" << f.path);
            REQUIRE(content == std::string(f.content));
        }
    }
}
