// Unit tests for export.cpp — `ezmk project export cmake` (CMakeLists.txt).
#define CATCH_AMALGAMATED_CUSTOM_MAIN
#include "catch2.hpp"
#include "test_helpers.hpp"
#include "ezmk/export.hpp"
#include "ezmk/config.hpp"
#include "ezmk/util.hpp"

#include <filesystem>
#include <fstream>
#include <string>

namespace fs = std::filesystem;
using namespace ezmk::config;
using namespace ezmk::export_gen;

namespace {

// Minimal executable project config.
EzConfig make_exe_config() {
    EzConfig cfg;
    cfg.project.name = "demo";
    cfg.project.type = "executable";
    cfg.project.version = "1.2.0";
    cfg.project.language = "C++17";
    cfg.compile.flags = {"-Wall", "-O2"};
    cfg.compile.include_dirs = {"include"};
    cfg.compile.src_dirs = {"src"};
    return cfg;
}

} // namespace

// ===================================================================
// Header / project-level mapping
// ===================================================================

TEST_CASE("export cmake: header + project() + add_executable", "[export]") {
    auto cfg = make_exe_config();
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("cmake_minimum_required(VERSION 3.16)") != std::string::npos);
    REQUIRE(t.find("Generated by `ezmk project export cmake`") != std::string::npos);
    REQUIRE(t.find("project(demo VERSION 1.2.0 LANGUAGES CXX)") != std::string::npos);
    REQUIRE(t.find("add_executable(demo ${demo_SOURCES})") != std::string::npos);
}

TEST_CASE("export cmake: static/shared library types", "[export]") {
    auto cfg = make_exe_config();
    cfg.project.type = "static";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("add_library(demo STATIC ${demo_SOURCES})") != std::string::npos);

    cfg.project.type = "shared";
    t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("add_library(demo SHARED ${demo_SOURCES})") != std::string::npos);
}

TEST_CASE("export cmake: utils type → WARNING, no target", "[export]") {
    auto cfg = make_exe_config();
    cfg.project.type = "utils";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("message(WARNING \"project type 'utils'") != std::string::npos);
    REQUIRE(t.find("add_executable") == std::string::npos);
    REQUIRE(t.find("add_library") == std::string::npos);
}

TEST_CASE("export cmake: header_only → INTERFACE", "[export]") {
    auto cfg = make_exe_config();
    cfg.project.header_only = true;
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("add_library(demo INTERFACE)") != std::string::npos);
}

TEST_CASE("export cmake: precompiled → IMPORTED", "[export]") {
    auto cfg = make_exe_config();
    cfg.project.precompiled = true;
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("add_library(demo IMPORTED)") != std::string::npos);
    REQUIRE(t.find("lib/libdemo.a") != std::string::npos);
}

TEST_CASE("export cmake: C project → LANGUAGES C + *.c glob + C_STANDARD", "[export]") {
    auto cfg = make_exe_config();
    cfg.project.language = "C11";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("LANGUAGES C)") != std::string::npos);
    REQUIRE(t.find("${CMAKE_CURRENT_SOURCE_DIR}/src/*.c") != std::string::npos);
}

// ===================================================================
// Compile mapping
// ===================================================================

TEST_CASE("export cmake: source glob default", "[export]") {
    auto cfg = make_exe_config();
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("file(GLOB_RECURSE demo_SOURCES CONFIGURE_DEPENDS") != std::string::npos);
    REQUIRE(t.find("${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp") != std::string::npos);
}

TEST_CASE("export cmake: --no-glob emits explicit source list", "[export]") {
    TempDir tmp;
    fs::create_directories(tmp.path / "src");
    { std::ofstream(tmp.path / "src" / "main.cpp") << "int main(){}\n"; }
    auto cfg = make_exe_config();
    ExportOptions opts;
    opts.use_glob = false;
    auto t = build_cmake_text(cfg, tmp.path, opts);
    REQUIRE(t.find("set(demo_SOURCES") != std::string::npos);
    REQUIRE(t.find("file(GLOB_RECURSE") == std::string::npos);
    REQUIRE(t.find("main.cpp") != std::string::npos);
}

TEST_CASE("export cmake: flags split — -std/-D/-I extracted, macros + ezmk_macros", "[export]") {
    auto cfg = make_exe_config();
    cfg.compile.flags = {"-Wall", "-std=c++17", "-DEZMK_EXTRA=1", "-Iextra_inc"};
    cfg.compile.macros = {{"DEBUG", "0"}, {"APP_NAME", "demo"}};
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    // -std → CXX_STANDARD; GNU off for plain -std=c++17.
    REQUIRE(t.find("CXX_STANDARD 17") != std::string::npos);
    REQUIRE(t.find("CXX_EXTENSIONS OFF") != std::string::npos);
    // -D from flags + [compile].macros + ezmk macros all land in definitions.
    REQUIRE(t.find("EZMK_EXTRA=1") != std::string::npos);
    REQUIRE(t.find("DEBUG=0") != std::string::npos);
    REQUIRE(t.find("APP_NAME=\"demo\"") != std::string::npos);
    REQUIRE(t.find("EZMK=1") != std::string::npos);
    // Plain flag stays in compile_options.
    REQUIRE(t.find("-Wall") != std::string::npos);
    // Split flags no longer appear verbatim.
    REQUIRE(t.find("-std=c++17") == std::string::npos);
    REQUIRE(t.find("-DEZMK_EXTRA=1") == std::string::npos);
    REQUIRE(t.find("-Iextra_inc") == std::string::npos);
}

TEST_CASE("export cmake: msvc_flags wrapped in genex", "[export]") {
    auto cfg = make_exe_config();
    cfg.compile.msvc_flags = {"/W4"};
    cfg.link.msvc_flags = {"/LTCG"};
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("COMPILE_LANG_AND_ID:CXX,MSVC") != std::string::npos);
    REQUIRE(t.find("/W4") != std::string::npos);
    REQUIRE(t.find("/LTCG") != std::string::npos);
}

TEST_CASE("export cmake: external include dir stays absolute + comment", "[export]") {
    CwdGuard guard;
    fs::path proj = fs::current_path();
    fs::path external = fs::temp_directory_path() / "ezmk_outside_inc_xyz";
    auto cfg = make_exe_config();
    cfg.compile.include_dirs = {"include", external.string()};
    auto t = build_cmake_text(cfg, proj, ExportOptions{});
    REQUIRE(t.find("outside the project root") != std::string::npos);
    REQUIRE(t.find(external.generic_string()) != std::string::npos);
}

// ===================================================================
// Link mapping
// ===================================================================

TEST_CASE("export cmake: link mapping — system_targets + -l/-L split", "[export]") {
    auto cfg = make_exe_config();
    cfg.link.system_targets = {"dl"};
    cfg.link.flags = {"-lpthread", "-Lextra_lib", "-s"};
    cfg.link.link_dirs = {"mylib"};
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("target_link_libraries(demo PRIVATE dl pthread)") != std::string::npos);
    REQUIRE(t.find("target_link_directories(demo PRIVATE") != std::string::npos);
    REQUIRE(t.find("target_link_options(demo PRIVATE -s)") != std::string::npos);
}

// ===================================================================
// Dependencies
// ===================================================================

TEST_CASE("export cmake: portable dep → find_package", "[export]") {
    auto cfg = make_exe_config();
    cfg.depends.libs.push_back({"openssl", {}});
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("find_package(OpenSSL QUIET)") != std::string::npos);
    REQUIRE(t.find("if(TARGET OpenSSL::SSL)") != std::string::npos);
}

TEST_CASE("export cmake: unaliased dep → upper-cased find_package placeholder", "[export]") {
    auto cfg = make_exe_config();
    cfg.depends.libs.push_back({"myweirdlib", {}});
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("find_package(MYWEIRDLIB QUIET)") != std::string::npos);
    REQUIRE(t.find("add manually") != std::string::npos);
}

TEST_CASE("export cmake: --resolve emits installed dep paths", "[export]") {
    CwdGuard guard;
    fs::path proj = fs::current_path();
    fs::create_directories(proj / ".ezmk" / "pkg" / "fmt" / "include");
    fs::create_directories(proj / ".ezmk" / "pkg" / "fmt" / "lib");
    { std::ofstream(proj / ".ezmk" / "pkg" / "fmt" / "include" / "fmt.hpp") << "x\n"; }
    { std::ofstream(proj / ".ezmk" / "pkg" / "fmt" / "lib" / "libfmt.a") << "x\n"; }

    auto cfg = make_exe_config();
    cfg.depends.libs.push_back({"fmt", {}});
    ExportOptions opts;
    opts.resolve = true;
    auto t = build_cmake_text(cfg, proj, opts);
    REQUIRE(t.find("resolved from installed package") != std::string::npos);
    REQUIRE(t.find(".ezmk/pkg/fmt/include") != std::string::npos);
    REQUIRE(t.find("libfmt.a") != std::string::npos);
}

// ===================================================================
// Hooks
// ===================================================================

TEST_CASE("export cmake: hooks → find_program + add_custom_command PRE/POST", "[export]") {
    auto cfg = make_exe_config();
    cfg.hooks.pre_build = "scripts/pre.lua";
    cfg.hooks.post_build = "scripts/post.lua";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    // dev.8: hooks run via the standalone ezmk-lua runtime.
    REQUIRE(t.find("find_program(EZMK_LUA ezmk-lua)") != std::string::npos);
    REQUIRE(t.find("if(NOT EZMK_LUA)") != std::string::npos);
    REQUIRE(t.find("message(WARNING \"[hooks] need 'ezmk-lua' on PATH") != std::string::npos);
    // pre_build → PRE_BUILD, post_build → POST_BUILD; script path rooted at the
    // CMake source dir; ctx injected via --project-root / --output.
    REQUIRE(t.find("add_custom_command(TARGET demo PRE_BUILD") != std::string::npos);
    REQUIRE(t.find("COMMAND ${EZMK_LUA} \"${CMAKE_CURRENT_SOURCE_DIR}/scripts/pre.lua\"")
            != std::string::npos);
    REQUIRE(t.find("--project-root ${CMAKE_CURRENT_SOURCE_DIR}") != std::string::npos);
    REQUIRE(t.find("--output $<TARGET_FILE:demo>") != std::string::npos);
    REQUIRE(t.find("add_custom_command(TARGET demo POST_BUILD") != std::string::npos);
    REQUIRE(t.find("\"${CMAKE_CURRENT_SOURCE_DIR}/scripts/post.lua\"") != std::string::npos);
    // The old "not exported" blanket warning must be gone.
    REQUIRE(t.find("NOT exported") == std::string::npos);
}

TEST_CASE("export cmake: on_failure stays a comment (no CMake failure hook)", "[export]") {
    auto cfg = make_exe_config();
    cfg.hooks.on_failure = "scripts/fail.lua";
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    // No pre/post hooks → no find_program / add_custom_command block at all.
    REQUIRE(t.find("find_program(EZMK_LUA") == std::string::npos);
    REQUIRE(t.find("add_custom_command") == std::string::npos);
    REQUIRE(t.find("on_failure \"scripts/fail.lua\"") != std::string::npos);
    REQUIRE(t.find("not exported") != std::string::npos);
}

TEST_CASE("export cmake: hook command inlines --profile", "[export]") {
    auto cfg = make_exe_config();
    cfg.hooks.post_build = "scripts/post.lua";
    cfg.compile_profiles["release"] = ProfileConfig{{}, {}, {}};
    ExportOptions opts;
    opts.profile = "release";
    auto t = build_cmake_text(cfg, fs::current_path(), opts);
    REQUIRE(t.find("--profile release") != std::string::npos);
}

TEST_CASE("export cmake: no hooks → no hooks section", "[export]") {
    auto cfg = make_exe_config();
    auto t = build_cmake_text(cfg, fs::current_path(), ExportOptions{});
    REQUIRE(t.find("[hooks]") == std::string::npos);
    REQUIRE(t.find("ezmk-lua") == std::string::npos);
}

// ===================================================================
// --profile
// ===================================================================

TEST_CASE("export cmake: --profile applies profile flags/macros", "[export]") {
    auto cfg = make_exe_config();
    cfg.compile_profiles["debug"] = ProfileConfig{{"-g"}, {}, {{"DEBUG", "1"}}};
    ExportOptions opts;
    opts.profile = "debug";
    auto t = build_cmake_text(cfg, fs::current_path(), opts);
    REQUIRE(t.find("-g") != std::string::npos);
    REQUIRE(t.find("DEBUG=1") != std::string::npos);
}

// ===================================================================
// Overwrite safety (export_cmake writes to disk)
// ===================================================================

TEST_CASE("export cmake: refuses overwrite without --overwrite", "[export]") {
    TempDir tmp;
    auto cfg = make_exe_config();
    { std::ofstream(tmp.path / "CMakeLists.txt") << "old\n"; }
    REQUIRE_THROWS_AS(export_cmake(cfg, tmp.path, ExportOptions{}), ezmk::fatal_error);
}

TEST_CASE("export cmake: --overwrite replaces existing file", "[export]") {
    TempDir tmp;
    auto cfg = make_exe_config();
    { std::ofstream(tmp.path / "CMakeLists.txt") << "old\n"; }
    ExportOptions opts;
    opts.overwrite = true;
    REQUIRE_NOTHROW(export_cmake(cfg, tmp.path, opts));
    auto content = ezmk::util::file_read(tmp.path / "CMakeLists.txt");
    REQUIRE(content.find("cmake_minimum_required") != std::string::npos);
}
