#!/usr/bin/env bash
set -euo pipefail

# EazyMake build script
# Works on MSYS2 (Windows), Linux, and macOS with g++.
#
# Usage:
#   bash build.sh                    # Normal build
#   bash build.sh test               # Build and run unit tests (skips [integration])
#   bash build.sh test-all           # Build and run all tests (unit + integration)
#   bash build.sh integration        # Build and run integration tests only
#   bash build.sh test -v            # Build and run tests (verbose)
#   bash build.sh -v                 # Verbose (show full compile command and flags)

cd "$(dirname "$0")"

# Generate embedded locale data (compile-time JSON → C++ strings)
if command -v python3 &> /dev/null; then
    python3 scripts/embed_locale.py locale/ > src/locale_data.cpp
elif command -v python &> /dev/null; then
    python scripts/embed_locale.py locale/ > src/locale_data.cpp
else
    echo "Warning: Python not found — locale data will be empty (English fallback only)" >&2
    # Must be inside ezmk::i18n namespace to match the declaration in i18n.cpp
    cat > src/locale_data.cpp << 'CPPEOF'
// Auto-generated stub — Python was not available at build time.
// Only hardcoded English fallback strings will be available.
namespace ezmk::i18n {
extern const std::map<std::string, std::string> embedded_locales = {};
}
CPPEOF
fi

# Version tag — embedded in the binary for "ezmk version" output.
# Write to a header file to avoid platform-specific -D quoting issues.
EZMK_VERSION="${EZMK_VERSION:-0.9.5}"
cat > include/ezmk/version.hpp << VEREOF
// Auto-generated by build.sh — DO NOT EDIT
#pragma once
#define EZMK_VERSION "${EZMK_VERSION}"
VEREOF

SRC="src/*.cpp src/vendor/*.c src/vendor/lua/*.c"
# Exclude main.cpp for tests (it has its own main() function; catch2_impl.cpp provides main)
TEST_SRC="src/build.cpp src/cache.cpp src/cli.cpp src/argparse.cpp src/config.cpp src/crypto.cpp src/file_watcher.cpp src/i18n.cpp src/locale_data.cpp src/lua_api.cpp src/pkg.cpp src/project.cpp src/repo.cpp src/toolchain.cpp src/util.cpp src/version.cpp src/vendor/*.c src/vendor/catch2_impl.cpp src/vendor/lua/*.c"
INCLUDES="-I include/ -I include/vendor/ -I include/vendor/lua/"
LUA_DEFINES="-DLUA_COMPAT_5_3"
OUTPUT="build/ezmk"
TEST_OUTPUT="build/test_ezmk"
CXX="${CXX:-g++}"
CC="${CC:-gcc}"
CXXFLAGS="${CXXFLAGS:--std=c++17}"

# Parse flags
VERBOSE=false
BUILD_TEST=false
RUN_TEST=false
BUILD_EZMK=false    # Whether to also build the ezmk binary (needed for integration tests)
TEST_FILTER=""       # Catch2 test filter (e.g. "~[integration]" or "[integration]")
for arg in "$@"; do
    case "$arg" in
        -v|--verbose) VERBOSE=true ;;
        test)
            BUILD_TEST=true
            RUN_TEST=true
            BUILD_EZMK=true          # Build ezmk so integration tests can use it
            TEST_FILTER="~[integration]"  # Default: skip integration tests
            ;;
        test-all)
            BUILD_TEST=true
            RUN_TEST=true
            BUILD_EZMK=true
            TEST_FILTER=""            # Run all tests (unit + integration)
            ;;
        integration)
            BUILD_TEST=true
            RUN_TEST=true
            BUILD_EZMK=true
            TEST_FILTER="[integration]"  # Run integration tests only
            ;;
        -h|--help)
            echo "Usage: bash build.sh [test|test-all|integration] [-v|--verbose]"
            echo "  test            Build and run unit tests (skips [integration])"
            echo "  test-all        Build and run all tests (unit + integration)"
            echo "  integration     Build and run integration tests only"
            echo "  -v, --verbose   Show full compile command"
            exit 0
            ;;
        *) echo "Unknown flag: $arg"; exit 1 ;;
    esac
done

# Platform-specific settings
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        # MSYS2 / Windows
        LIBS="-lwinhttp"
        LDFLAGS="-static"
        ;;
    Linux)
        LIBS=""
        LDFLAGS="-static"
        ;;
    Darwin)
        # macOS — static linking is not fully supported, use dynamic
        LIBS=""
        LDFLAGS=""
        ;;
    *)
        echo "Warning: unknown platform, trying generic build" >&2
        LIBS=""
        LDFLAGS=""
        ;;
esac

mkdir -p build

if $BUILD_TEST; then
    # ── Build ezmk binary first (needed for integration tests) ────────────
    if $BUILD_EZMK; then
        # Only build ezmk if it doesn't exist or source is newer
        NEED_EZMK_BUILD=false
        if [ ! -f "$OUTPUT" ]; then
            NEED_EZMK_BUILD=true
        else
            # Check if any source is newer than the binary
            for src in src/*.cpp src/vendor/*.c src/vendor/lua/*.c; do
                if [ "$src" -nt "$OUTPUT" ]; then
                    NEED_EZMK_BUILD=true
                    break
                fi
            done
        fi

        if $NEED_EZMK_BUILD; then
            echo "=== Building ezmk binary (required for integration tests) ==="
            if $VERBOSE; then
                echo "Compiler: $CXX"
                echo "Flags:    $CXXFLAGS"
                echo "Sources:  $SRC"
                echo "Includes: $INCLUDES"
                echo "Libs:     $LIBS"
                echo "LDFlags:  $LDFLAGS"
                echo "Output:   $OUTPUT"
                echo ""
            fi
            $CXX $CXXFLAGS $SRC $INCLUDES $LUA_DEFINES -o "$OUTPUT" $LIBS $LDFLAGS
            echo "=== ezmk build successful: $OUTPUT ==="
            echo ""
        else
            echo "=== ezmk binary is up to date: $OUTPUT ==="
            echo ""
        fi
    fi

    # ── Build test binary ──────────────────────────────────────────────────
    echo "=== Building EazyMake test suite ==="
    if $VERBOSE; then
        echo "Compiler: $CXX"
        echo "Flags:    $CXXFLAGS"
        echo "TestSrc:  $TEST_SRC"
        echo "Includes: $INCLUDES"
        echo "Libs:     $LIBS"
        echo "LDFlags:  $LDFLAGS"
        echo "Output:   $TEST_OUTPUT"
        echo ""
    fi

    $CXX $CXXFLAGS test/test_*.cpp $TEST_SRC $INCLUDES $LUA_DEFINES -o "$TEST_OUTPUT" $LIBS $LDFLAGS

    echo "=== Test build successful: $TEST_OUTPUT ==="

    # ── Run tests ──────────────────────────────────────────────────────────
    if $RUN_TEST; then
        # Set ezmk binary path so integration tests can find it
        EZMK_TEST_BIN="$(pwd)/$OUTPUT"
        export EZMK_TEST_BIN

        echo ""
        if [ -n "$TEST_FILTER" ]; then
            echo "=== Running tests (filter: $TEST_FILTER) ==="
            ./"$TEST_OUTPUT" --verbosity high "$TEST_FILTER" || true
        else
            echo "=== Running all tests ==="
            ./"$TEST_OUTPUT" --verbosity high || true
        fi
        echo ""
        echo "=== Tests complete ==="
    fi
else
    if $VERBOSE; then
        echo "=== Building EazyMake ==="
        echo "Compiler: $CXX"
        echo "Flags:    $CXXFLAGS"
        echo "Sources:  $SRC"
        echo "Includes: $INCLUDES"
        echo "Libs:     $LIBS"
        echo "LDFlags:  $LDFLAGS"
        echo "Output:   $OUTPUT"
        echo ""
    fi

    $CXX $CXXFLAGS $SRC $INCLUDES $LUA_DEFINES -o "$OUTPUT" $LIBS $LDFLAGS

    echo "=== Build successful: $OUTPUT ==="
fi
