// Auto-generated by scripts/embed_logo.py — DO NOT EDIT
#pragma once
#ifndef EZMK_LOGO_GEN_H
#define EZMK_LOGO_GEN_H

namespace ezmk {

// ASCII logo loaded from res/logo.txt at compile time.
inline constexpr const char* EZMK_LOGO =
R"(    ______                  __  ___      __
   / ____/___ _____  __  __/  |/  /___ _/ /_____
  / __/ / __ `/_  / / / / / /|_/ / __ `/ //_/ _ \
 / /___/ /_/ / / /_/ /_/ / /  / / /_/ / ,< /  __/
/_____/\__,_/ /___/\__, /_/  /_/\__,_/_/|_|\___/
                  /____/)";

} // namespace ezmk

#endif // EZMK_LOGO_GEN_H
