#!/usr/bin/env python3
"""
embed_locale.py — Convert locale/*.json into a C++ source file that embeds
the locale data as compile-time string constants.

Usage:
  python scripts/embed_locale.py locale/ > src/locale_data.cpp

The output defines:
  const std::map<std::string, std::string> embedded_locales = { ... };
"""

import sys
import os
import json

def embed_json_string(s: str) -> str:
    """Escape a JSON string for embedding in C++ raw string literals.

    Uses C++11 raw string literals: R"delim(...)delim". We pick a delimiter
    that doesn't appear in the content.
    """
    # Find a delimiter that doesn't appear in the content
    for delim in ["LC", "LOCALE", "JSON", "EOL"]:
        if delim not in s:
            return f'R"{delim}({s}){delim}"'
    # Fallback: use a long random-ish delimiter
    return f'R"LCJSONEND({s})LCJSONEND"'

def main():
    if len(sys.argv) < 2:
        print("Usage: python embed_locale.py <locale_dir>", file=sys.stderr)
        sys.exit(1)

    locale_dir = sys.argv[1]
    if not os.path.isdir(locale_dir):
        print(f"Error: {locale_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    # Collect all JSON files
    entries = {}
    for fname in sorted(os.listdir(locale_dir)):
        if not fname.endswith(".json"):
            continue
        filepath = os.path.join(locale_dir, fname)
        lang = fname[:-5]  # strip ".json"

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        # Validate JSON
        try:
            parsed = json.loads(content)
            # Basic structure check
            if "strings" not in parsed:
                print(f"Warning: {fname} has no 'strings' key", file=sys.stderr)
            if "meta" not in parsed:
                print(f"Warning: {fname} has no 'meta' key", file=sys.stderr)
        except json.JSONDecodeError as e:
            print(f"Error: {fname} is not valid JSON: {e}", file=sys.stderr)
            sys.exit(1)

        entries[lang] = embed_json_string(content)

    # Generate C++ source
    print("// Auto-generated by scripts/embed_locale.py — DO NOT EDIT")
    print("// Embeds locale/*.json as compile-time string constants.")
    print()
    print('#include <map>')
    print('#include <string>')
    print()
    print("namespace ezmk::i18n {")
    print()
    print("// extern ensures external linkage (overrides the weak definition in i18n.cpp)")
    print("extern const std::map<std::string, std::string> embedded_locales = {")

    for lang, escaped in entries.items():
        print(f'    {{"{lang}", {escaped}}},')

    print("};")
    print()
    print("} // namespace ezmk::i18n")


if __name__ == "__main__":
    main()
