#!/usr/bin/env python3
"""embed_logo.py — Embed res/logo.txt as a C++ header constexpr string.

Usage: python3 scripts/embed_logo.py res/logo.txt include/ezmk/logo.gen.h

Follows the same pattern as scripts/embed_locale.py:
generate a .gen.h file with include guard that is compiled into the binary.
"""

import sys
import os


def embed_logo(input_path: str, output_path: str) -> None:
    if not os.path.isfile(input_path):
        print(f"embed_logo.py: error: input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    with open(input_path, "r", encoding="utf-8") as f:
        logo_text = f.read()

    # Strip trailing blank lines (keep trailing newline from file end only)
    logo_text = logo_text.rstrip("\n")

    guard = "EZMK_LOGO_GEN_H"
    content = f"""// Auto-generated by scripts/embed_logo.py — DO NOT EDIT
#pragma once
#ifndef {guard}
#define {guard}

namespace ezmk {{

// ASCII logo loaded from res/logo.txt at compile time.
inline constexpr const char* EZMK_LOGO =
R"({logo_text})";

}} // namespace ezmk

#endif // {guard}
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"embed_logo.py: wrote {output_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 scripts/embed_logo.py <logo.txt> <output.gen.h>", file=sys.stderr)
        sys.exit(1)
    embed_logo(sys.argv[1], sys.argv[2])
