#!/usr/bin/env python3
"""
embed_examples.py — Embed the examples/ source tree into a C++ source file
(src/example_data.cpp) that is compiled into the binary. Follows the same
pattern as embed_locale.py / embed_logo.py: read source files at build time,
emit C++ data.

Usage:
  python3 scripts/embed_examples.py examples/ > src/example_data.cpp

Each example directory must contain a description.txt (one-line description,
shown by `ezmk example list`). All other files under the directory are embedded
as {path, content} pairs (paths use forward slashes).

The output defines:
  const std::vector<ezmk::example::Example>& embedded_examples();
"""

import sys
import os


def raw_string(content: str) -> str:
    """Embed content as a C++ raw string literal with a stable delimiter."""
    return f'R"EZX({content})EZX"'


def main():
    # Force UTF-8 on stdout (Chinese descriptions/content): see embed_locale.py
    # for the pre.3 rationale on Windows CI runners.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    if len(sys.argv) < 2:
        print("Usage: python3 embed_examples.py <examples_dir>", file=sys.stderr)
        sys.exit(1)

    examples_dir = sys.argv[1]
    if not os.path.isdir(examples_dir):
        print(f"Error: {examples_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    examples = []
    for entry in sorted(os.listdir(examples_dir)):
        edir = os.path.join(examples_dir, entry)
        if not os.path.isdir(edir):
            continue  # README.md etc.

        description = ""
        desc_path = os.path.join(edir, "description.txt")
        if os.path.isfile(desc_path):
            with open(desc_path, "r", encoding="utf-8", newline="") as f:
                description = f.read().strip()

        files = []
        for root, dirs, fnames in os.walk(edir):
            dirs.sort()
            for fname in sorted(fnames):
                if fname == "description.txt":
                    continue
                fpath = os.path.join(root, fname)
                rel = os.path.relpath(fpath, edir).replace("\\", "/")
                # newline="" — keep the file's original line endings (CRLF on a
                # Windows checkout). Text mode would normalize \r\n → \n and the
                # embedded table would drift from the source tree (the
                # anti-drift test compares byte-for-byte).
                with open(fpath, "r", encoding="utf-8", newline="") as f:
                    content = f.read()
                files.append((rel, content))

        examples.append((entry, description, files))

    out = []
    out.append("// Auto-generated by scripts/embed_examples.py — DO NOT EDIT")
    out.append('#include "ezmk/example.hpp"')
    out.append("")
    out.append("namespace ezmk::example {")
    out.append("")
    out.append("const std::vector<Example>& embedded_examples() {")
    out.append("    static const std::vector<Example> examples = {")
    for name, desc, files in examples:
        out.append("        {")
        out.append(f"            {raw_string(name)},")
        out.append(f"            {raw_string(desc)},")
        out.append("            {")
        for rel, content in files:
            out.append(f"                {{ {raw_string(rel)}, {raw_string(content)} }},")
        out.append("            },")
        out.append("        },")
    out.append("    };")
    out.append("    return examples;")
    out.append("}")
    out.append("")
    out.append("} // namespace ezmk::example")

    # Write raw bytes: on Windows, print()/stdout in redirected (text) mode
    # translates every \n to \r\n, which would corrupt the raw string contents
    # (a CRLF source line would become CR+CR+LF). buffer.write emits the exact
    # bytes so the embedded table matches the source files byte-for-byte.
    sys.stdout.buffer.write(("\n".join(out) + "\n").encode("utf-8"))


if __name__ == "__main__":
    main()
