#include "ezmk/export.hpp"
#include "ezmk/build.hpp"     // build::generate_ezmk_macros
#include "ezmk/util.hpp"
#include "ezmk/pkg.hpp"
#include "ezmk/i18n.hpp"
#include "ezmk/toolchain.hpp"
#include "nlohmann_json.hpp"
#include "pkg_alias.hpp"      // 共享包别名表（dev.2 export / dev.4 import）

#include <algorithm>
#include <cctype>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace ezmk::export_gen {
namespace fs = std::filesystem;

namespace {

// Mirror build.cpp::escape_macro_value — string macro values are quoted (and
// backslash-escaped), integer/empty values are bare. This keeps the generated
// definitions byte-identical to what `ezmk build` injects.
std::string escape_macro_value(const std::string& val) {
    if (val.empty()) return val;
    bool plain_int = std::all_of(val.begin(), val.end(),
                                 [](char c) { return c >= '0' && c <= '9'; });
    if (plain_int) return val;
    std::string escaped;
    for (char c : val) {
        if (c == '"' || c == '\\') escaped += '\\';
        escaped += c;
    }
    return "\"" + escaped + "\"";
}

// CMake expression for a path: relative dirs / paths under the project root
// become `${CMAKE_CURRENT_SOURCE_DIR}/<rel>` (portable); paths outside the
// project root (e.g. via `@link:` to an external dir) stay absolute.
// Returns "in_root=false" in `outside` for those external paths.
std::string cmake_path(const fs::path& p, const fs::path& root, bool& outside) {
    outside = false;
    fs::path abs = p.is_absolute() ? p : (root / p);
    abs = abs.lexically_normal();
    fs::path root_abs = fs::absolute(root).lexically_normal();
    std::error_code ec;
    auto rel = fs::relative(abs, root_abs, ec);
    if (!ec && !rel.empty() && rel.generic_string().find("..") == std::string::npos) {
        return "${CMAKE_CURRENT_SOURCE_DIR}/" + rel.generic_string();
    }
    outside = true;
    return abs.generic_string();
}

// Apply a build profile's flags/macros on top of the base compile section.
config::CompileSection effective_compile(const config::EzConfig& cfg,
                                         const std::string& profile) {
    config::CompileSection c = cfg.compile;
    if (profile.empty()) return c;
    auto it = cfg.compile_profiles.find(profile);
    if (it == cfg.compile_profiles.end()) {
        util::fatal(std::string("unknown profile: '") + profile +
                    "'. No such compile profile in ezmk.toml.");
    }
    c.flags.insert(c.flags.end(), it->second.flags.begin(), it->second.flags.end());
    c.msvc_flags.insert(c.msvc_flags.end(),
                        it->second.msvc_flags.begin(), it->second.msvc_flags.end());
    for (const auto& [k, v] : it->second.macros) c.macros[k] = v;
    return c;
}

config::LinkSection effective_link(const config::EzConfig& cfg,
                                   const std::string& profile) {
    config::LinkSection l = cfg.link;
    if (profile.empty()) return l;
    auto it = cfg.link_profiles.find(profile);
    if (it == cfg.link_profiles.end()) return l;  // compile profile matched; link may be absent
    l.flags.insert(l.flags.end(), it->second.flags.begin(), it->second.flags.end());
    l.msvc_flags.insert(l.msvc_flags.end(),
                        it->second.msvc_flags.begin(), it->second.msvc_flags.end());
    return l;
}

// （包别名表已抽至 pkg_alias.hpp，见文件顶部 include）

// Locate an installed package dir across project → user → global scopes.
// Returns empty if not installed. Used by `--resolve`.
fs::path find_installed_pkg(const std::string& name) {
    for (const auto& base : pkg::pkg_search_dirs(
             {cli::Scope::Project, cli::Scope::User, cli::Scope::Global})) {
        fs::path cand = base / name;
        if (fs::exists(cand / "include") || fs::exists(cand / "lib")) {
            return cand;
        }
    }
    return {};
}

} // namespace

std::string build_cmake_text(const config::EzConfig& cfg,
                             const fs::path& project_root,
                             const ExportOptions& opts) {
    auto lang = config::parse_language(cfg.project.language);
    const bool is_cpp = (lang.compiler != "gcc");  // "g++" → C++
    const std::string cmake_lang = is_cpp ? "CXX" : "C";
    const std::string target = cfg.project.name;

    // CMake variable name for the source list — sanitize to [A-Za-z0-9_].
    std::string src_var = target + "_SOURCES";
    for (auto& c : src_var) {
        if (!std::isalnum(static_cast<unsigned char>(c)) && c != '_') c = '_';
    }

    // 1.2.0-dev.3: no --profile → fall back to [compile].default_profile (if set)
    const std::string profile =
        opts.profile.empty() ? cfg.compile.default_profile : opts.profile;
    auto compile = effective_compile(cfg, profile);
    auto link = effective_link(cfg, profile);

    std::ostringstream os;
    os << "cmake_minimum_required(VERSION 3.16)\n";
    os << "# Generated by `ezmk project export cmake` from ezmk.toml — "
          "do not hand-edit; regenerate.\n";
    // 1.2.0-dev.11: CMake project() VERSION accepts only a numeric dotted
    // version — a pre-release like "1.2.0-dev.10" would fail at configure.
    bool version_numeric = false;
    if (!cfg.project.version.empty()) {
        version_numeric = std::all_of(cfg.project.version.begin(),
                                      cfg.project.version.end(),
                                      [](char c) { return (c >= '0' && c <= '9') || c == '.'; });
    }
    os << "project(" << target;
    if (version_numeric) os << " VERSION " << cfg.project.version;
    os << " LANGUAGES " << cmake_lang << ")\n";
    if (!cfg.project.version.empty() && !version_numeric) {
        os << "# VERSION omitted: '" << cfg.project.version
           << "' is not a numeric version\n";
    }

    // `utils` is a package format with no C++ target — nothing to export.
    if (cfg.project.type == "utils") {
        os << "\nmessage(WARNING \"project type 'utils' has no C++ target — "
              "nothing exported\")\n";
        return os.str();
    }

    const std::vector<std::string> extensions = is_cpp
        ? std::vector<std::string>{"cpp", "cc", "cxx", "c++"}
        : std::vector<std::string>{"c"};

    // ---- Sources ----
    os << "\n# --- Sources ---\n";
    if (opts.use_glob) {
        os << "file(GLOB_RECURSE " << src_var << " CONFIGURE_DEPENDS\n";
        std::vector<std::string> src_dirs = compile.src_dirs;
        if (src_dirs.empty()) src_dirs.push_back("src");
        for (const auto& d : src_dirs) {
            bool outside = false;
            std::string expr = cmake_path(d, project_root, outside);
            for (const auto& ext : extensions) {
                os << "    " << expr << "/*." << ext << "\n";
            }
        }
        os << ")\n";
    } else {
        // --no-glob: explicit, deterministic file list.
        std::vector<std::string> src_dirs = compile.src_dirs;
        if (src_dirs.empty()) src_dirs.push_back("src");
        os << "set(" << src_var << "\n";
        for (const auto& d : src_dirs) {
            fs::path dir = fs::path(d).is_relative() ? (project_root / d) : fs::path(d);
            std::error_code ec;
            for (auto it = fs::recursive_directory_iterator(dir, ec);
                 !ec && it != fs::recursive_directory_iterator(); it.increment(ec)) {
                if (!it->is_regular_file()) continue;
                std::string ext = it->path().extension().string();
                if (ext.size() > 1) ext = ext.substr(1);  // strip leading '.'
                if (std::find(extensions.begin(), extensions.end(), ext) == extensions.end())
                    continue;
                bool outside = false;
                os << "    " << cmake_path(it->path(), project_root, outside) << "\n";
            }
        }
        os << ")\n";
    }

    // ---- Target ----
    if (cfg.project.header_only) {
        os << "\n# header-only package — interface library, no compile/link steps.\n";
        os << "add_library(" << target << " INTERFACE)\n";
        if (!compile.include_dirs.empty()) {
            os << "target_include_directories(" << target << " INTERFACE";
            for (const auto& d : compile.include_dirs) {
                bool outside = false;
                os << " " << cmake_path(d, project_root, outside);
            }
            os << ")\n";
        }
        return os.str();
    }
    if (cfg.project.precompiled) {
        os << "\n# precompiled package — imported static library.\n";
        // 1.2.0-dev.11: resolve the actual archive for the current platform /
        // toolchain (dev.10 os-arch[-compiler][-abi] naming) instead of
        // hardcoding lib<name>.a — a package may ship only tagged archives,
        // and MSVC uses .lib.
        std::string archive_name = "lib" + target + ".a";
        try {
            auto sel = pkg::select_precompiled_archive(project_root / "lib", target);
            archive_name = sel.filename().string();
        } catch (const std::exception& e) {
            os << "# precompiled archive selection failed: " << e.what() << "\n";
        }
        os << "add_library(" << target << " IMPORTED)\n";
        os << "set_target_properties(" << target << " PROPERTIES\n";
        os << "    IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/lib/" << archive_name << "\n";
        os << "    INTERFACE_INCLUDE_DIRECTORIES ${CMAKE_CURRENT_SOURCE_DIR}/include\n";
        os << ")\n";
        return os.str();
    }
    if (cfg.project.type == "static") {
        os << "\nadd_library(" << target << " STATIC ${" << src_var << "})\n";
    } else if (cfg.project.type == "shared") {
        os << "\nadd_library(" << target << " SHARED ${" << src_var << "})\n";
    } else {
        os << "\nadd_executable(" << target << " ${" << src_var << "})\n";
    }

    // ---- Compile ----
    // Split `[compile].flags` into their semantic buckets so CMake manages each
    // concern in the idiomatic place (same split the design doc specifies).
    std::vector<std::string> include_dirs = compile.include_dirs;
    std::vector<std::string> defs;
    std::vector<std::string> opt_flags;
    int std_num = 0;
    bool gnu_ext = lang.gnu_extensions;

    auto digest_std = [&](const std::string& s) {
        std::string st = s;
        if (st.rfind("gnu", 0) == 0) { gnu_ext = true; st = st.substr(3); }
        std::string digits;
        for (char c : st) if (c >= '0' && c <= '9') digits += c;
        if (!digits.empty()) std_num = std::stoi(digits);
    };

    for (const auto& f : compile.flags) {
        if (f.rfind("-std=", 0) == 0) {
            digest_std(f.substr(5));
        } else if (f.rfind("-I", 0) == 0 && f.size() > 2) {
            include_dirs.push_back(f.substr(2));
        } else if (f.rfind("-D", 0) == 0 && f.size() > 2) {
            defs.push_back(f.substr(2));
        } else {
            opt_flags.push_back(f);
        }
    }
    if (std_num == 0) {
        // 1.3.1: read the parsed minimum standard directly — the old bare
        // digit extraction mangled range languages ("CPP11..CPP17" → 1117).
        std_num = lang.min_ver;
    }

    // ezmk standard macros + [compile].macros + -D flags.
    if (compile.ezmk_macros) {
        for (const auto& m : build::generate_ezmk_macros(cfg)) {
            if (m.rfind("-D", 0) == 0) defs.push_back(m.substr(2));
        }
    }
    for (const auto& [k, v] : compile.macros) {
        defs.push_back(v.empty() ? k : k + "=" + escape_macro_value(v));
    }

    os << "\n# --- Compile ---\n";
    if (!include_dirs.empty()) {
        std::vector<std::string> external;
        os << "target_include_directories(" << target << " PRIVATE";
        for (const auto& d : include_dirs) {
            bool outside = false;
            std::string expr = cmake_path(d, project_root, outside);
            if (outside) external.push_back(expr);
            os << " " << expr;
        }
        os << ")\n";
        if (!external.empty()) {
            os << "# include dirs outside the project root (e.g. @link:):";
            for (const auto& e : external) os << " " << e;
            os << "\n";
        }
    }
    if (!defs.empty()) {
        os << "target_compile_definitions(" << target << " PRIVATE";
        for (const auto& d : defs) os << " " << d;
        os << ")\n";
    }
    if (std_num > 0) {
        // 1.4.0-dev.4: 能力确认——导出的标准超目标工具链能力 → 注释警告
        // （不静默改值，CMake 项目可自行决定；检测为静态缓存，未知版本不警告）。
        auto cap_note = std_capability_note(is_cpp ? "CXX" : "C", std_num,
                                            toolchain::detect_toolchain());
        if (!cap_note.empty()) os << cap_note << "\n";
        os << "set_target_properties(" << target << " PROPERTIES "
           << (is_cpp ? "CXX_STANDARD " : "C_STANDARD ") << std_num
           << " " << (is_cpp ? "CXX_STANDARD_REQUIRED" : "C_STANDARD_REQUIRED")
           << " ON)\n";
        os << "set_target_properties(" << target << " PROPERTIES "
           << (is_cpp ? "CXX_EXTENSIONS " : "C_EXTENSIONS ")
           << (gnu_ext ? "ON" : "OFF") << ")\n";
    }
    if (!opt_flags.empty()) {
        os << "target_compile_options(" << target << " PRIVATE";
        for (const auto& f : opt_flags) os << " " << f;
        os << ")\n";
    }
    if (!compile.msvc_flags.empty()) {
        os << "target_compile_options(" << target << " PRIVATE "
           << "$<$<COMPILE_LANG_AND_ID:" << cmake_lang << ",MSVC>:";
        for (const auto& f : compile.msvc_flags) os << " " << f;
        os << ">)\n";
    }
    if (!cfg.project.stdlib.empty() && cfg.project.stdlib != "libstdc++") {
        os << "target_compile_options(" << target << " PRIVATE "
           << "$<$<COMPILE_LANG_AND_ID:" << cmake_lang
           << ",Clang>:-stdlib=" << cfg.project.stdlib << ">)\n";
    }

    // ---- Link ----
    std::vector<std::string> link_dirs = link.link_dirs;
    std::vector<std::string> link_libs = link.system_targets;
    std::vector<std::string> link_opts;
    for (const auto& f : link.flags) {
        if (f.rfind("-l", 0) == 0 && f.size() > 2) {
            link_libs.push_back(f.substr(2));
        } else if (f.rfind("-L", 0) == 0 && f.size() > 2) {
            link_dirs.push_back(f.substr(2));
        } else {
            link_opts.push_back(f);
        }
    }

    os << "\n# --- Link ---\n";
    if (!link_dirs.empty()) {
        os << "target_link_directories(" << target << " PRIVATE";
        for (const auto& d : link_dirs) {
            bool outside = false;
            os << " " << cmake_path(d, project_root, outside);
        }
        os << ")\n";
    }
    if (!link_libs.empty()) {
        os << "target_link_libraries(" << target << " PRIVATE";
        for (const auto& l : link_libs) os << " " << l;
        os << ")\n";
    }
    if (!link_opts.empty()) {
        os << "target_link_options(" << target << " PRIVATE";
        for (const auto& f : link_opts) os << " " << f;
        os << ")\n";
    }
    if (!link.msvc_flags.empty()) {
        os << "target_link_options(" << target << " PRIVATE "
           << "$<$<COMPILE_LANG_AND_ID:" << cmake_lang << ",MSVC>:";
        for (const auto& f : link.msvc_flags) os << " " << f;
        os << ">)\n";
    }

    // ---- Dependencies (best-effort) ----
    auto emit_deps = [&](const std::vector<config::DependsEntry>& deps) {
        for (const auto& dep : deps) {
            const std::string& name = dep.name;
            os << "\n# --- dependency: " << name << " ---\n";
            if (opts.resolve) {
                fs::path pkg_dir = find_installed_pkg(name);
                if (pkg_dir.empty()) {
                    os << "# package '" << name << "' not found installed — add manually\n";
                    continue;
                }
                // Concrete paths (this machine only — not portable).
                os << "# resolved from installed package (--resolve; machine-specific)\n";
                os << "target_include_directories(" << target << " PRIVATE "
                   << (pkg_dir / "include").generic_string() << ")\n";
                // 1.2.0-dev.11: use the actual selected archive (tagged
                // os-arch[-compiler][-abi] naming / MSVC .lib) rather than a
                // hardcoded lib<name>.a.
                std::string resolved_archive =
                    (pkg_dir / "lib" / ("lib" + name + ".a")).generic_string();
                try {
                    auto sel = pkg::select_precompiled_archive(pkg_dir / "lib", name);
                    resolved_archive = sel.generic_string();
                } catch (const std::exception& e) {
                    os << "# precompiled archive selection failed: " << e.what() << "\n";
                }
                os << "target_link_libraries(" << target << " PRIVATE "
                   << resolved_archive << ")\n";
                continue;
            }
            auto it = std::find_if(std::begin(kPkgAliases), std::end(kPkgAliases),
                                   [&](const PkgAlias& a) { return name == a.pkg; });
            if (it != std::end(kPkgAliases)) {
                os << "find_package(" << it->find << " QUIET)\n";
                os << "if(TARGET " << it->target << ")\n";
                os << "    target_link_libraries(" << target << " PRIVATE "
                   << it->target << ")\n";
                os << "else()\n";
                os << "    message(STATUS \"dependency '" << name
                   << "': CMake target unknown — add manually\")\n";
                os << "endif()\n";
            } else {
                std::string pkg_upper = name;
                for (auto& c : pkg_upper)
                    c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
                os << "find_package(" << pkg_upper << " QUIET)\n";
                os << "if(TARGET " << pkg_upper << ")\n";
                os << "    target_link_libraries(" << target << " PRIVATE "
                   << pkg_upper << ")\n";
                os << "else()\n";
                os << "    message(STATUS \"dependency '" << name
                   << "': CMake target unknown — add manually\")\n";
                os << "endif()\n";
            }
        }
    };
    emit_deps(cfg.depends.libs);
    emit_deps(cfg.depends.want);

    // ---- hooks (run via ezmk-lua, EazyMake standalone Lua runtime) ----
    // dev.2 只注释 + WARNING；dev.8 起 pre/post 经 find_program + add_custom_command
    // 调用独立无沙箱运行时 ezmk-lua 复现 ezmk build 的钩子后处理（best-effort：
    // 未安装 ezmk-lua 时回退 warning，不硬依赖 ezmk 已安装）。
    const auto& hooks = cfg.hooks;
    const bool has_pre_post = !hooks.pre_build.empty() || !hooks.post_build.empty();
    if (has_pre_post || !hooks.on_failure.empty()) {
        os << "\n# --- hooks (run via ezmk-lua, EazyMake standalone Lua runtime) ---\n";
        if (has_pre_post) {
            os << "find_program(EZMK_LUA ezmk-lua)\n";
            os << "if(NOT EZMK_LUA)\n";
            os << "    message(WARNING \"[hooks] need 'ezmk-lua' on PATH — hook "
                  "post-processing will not run.\")\n";
            os << "else()\n";
            auto emit_hook_cmd = [&](const std::string& kind,
                                     const std::string& hook_path) {
                // 钩子路径相对项目根 → ${CMAKE_CURRENT_SOURCE_DIR}/<path>（与
                // --project-root 一致）；绝对路径原样保留。
                std::string script =
                    fs::path(hook_path).is_absolute()
                        ? hook_path
                        : "${CMAKE_CURRENT_SOURCE_DIR}/" + hook_path;
                os << "    add_custom_command(TARGET " << target << " " << kind << "\n";
                os << "        COMMAND ${EZMK_LUA} \"" << script << "\"\n";
                os << "                --project-root ${CMAKE_CURRENT_SOURCE_DIR}\n";
                if (!profile.empty()) os << "                --profile " << profile << "\n";
                os << "                --output $<TARGET_FILE:" << target << ">)\n";
            };
            if (!hooks.pre_build.empty())  emit_hook_cmd("PRE_BUILD",  hooks.pre_build);
            if (!hooks.post_build.empty()) emit_hook_cmd("POST_BUILD", hooks.post_build);
            os << "endif()\n";
        }
        // on_failure：CMake 无原生「构建失败」钩子 — 保持注释 + 说明（范围边界，同 dev.2）。
        if (!hooks.on_failure.empty()) {
            os << "# on_failure \"" << hooks.on_failure << "\" — CMake has no native "
                  "failure hook; not exported (same as dev.2).\n";
        }
    }

    return os.str();
}

int export_cmake(const config::EzConfig& cfg,
                 const fs::path& project_root,
                 const ExportOptions& opts) {
    fs::path out = opts.output.empty()
        ? (project_root / "CMakeLists.txt")
        : (fs::path(opts.output).is_relative()
               ? (project_root / fs::path(opts.output))
               : fs::path(opts.output));

    // Overwrite safety: refuse unless --overwrite was given.
    if (fs::exists(out) && !opts.overwrite) {
        util::fatal(ezmk::i18n::I18nKey::export_exists_refuse,
                    {{"path", out.string()}});
    }

    std::string text = build_cmake_text(cfg, project_root, opts);

    // Atomic write (temp → rename), mirroring cache/compile_db writers.
    auto tmp = out;
    tmp += ".tmp";
    util::file_write(tmp, text);
    std::error_code ec;
    fs::rename(tmp, out, ec);
    if (ec) util::file_write(out, text);

    util::info(ezmk::i18n::I18nKey::export_written, {{"path", out.string()}});
    // dev.8: hooks 现经 ezmk-lua 导出（best-effort），提示用户该运行时依赖。
    if (!cfg.hooks.pre_build.empty() || !cfg.hooks.post_build.empty()) {
        util::info(ezmk::i18n::I18nKey::export_hook_note);
    }
    return 0;
}

// ===================================================================
// 1.4.0-dev.1: `ezmk project export vscode` — .vscode/ debug config trio
// ===================================================================

HostPlatform current_host_platform() {
#if defined(_WIN32)
    return HostPlatform::Windows;
#elif defined(__APPLE__)
    return HostPlatform::MacOs;
#else
    return HostPlatform::Linux;
#endif
}

VscodeDebugger select_vscode_debugger(HostPlatform plat,
                                      toolchain::CompilerFamily family,
                                      const std::string& project_name) {
    VscodeDebugger d;
    d.program = "build/" + project_name;
    if (plat == HostPlatform::Windows) d.program += ".exe";

    // macOS + Clang (Apple toolchain) → native lldb (design §3.2).
    if (plat == HostPlatform::MacOs && family == toolchain::CompilerFamily::Clang) {
        d.type = "lldb";
        return d;
    }
    // Windows + MSVC → cppvsdbg (needs VS Code C++ extension / VS — doc note).
    if (plat == HostPlatform::Windows && family == toolchain::CompilerFamily::Msvc) {
        d.type = "cppvsdbg";
        return d;
    }
    // Everything else → cppdbg over the MI protocol; debugger by detected family.
    d.type = "cppdbg";
    d.mi_debugger_path =
        (family == toolchain::CompilerFamily::Clang) ? "lldb" : "gdb";
    return d;
}

VscodeFiles build_vscode_files(const config::EzConfig& cfg,
                               const fs::path& project_root,
                               const ExportOptions& opts) {
    // Profile resolution mirrors export cmake: explicit --profile, else
    // [compile].default_profile. Unknown profile → fatal (same as
    // effective_compile, so tasks never reference a nonexistent profile).
    const std::string profile =
        opts.profile.empty() ? cfg.compile.default_profile : opts.profile;
    if (!profile.empty() &&
        cfg.compile_profiles.find(profile) == cfg.compile_profiles.end()) {
        util::fatal(std::string("unknown profile: '") + profile +
                    "'. No such compile profile in ezmk.toml.");
    }

    auto tc = toolchain::detect_toolchain();
    VscodeDebugger dbg =
        select_vscode_debugger(current_host_platform(), tc.family, cfg.project.name);

    // ---- launch.json (design §3.2) ----
    nlohmann::json launch = nlohmann::json::object();
    launch["version"] = "0.2.0";
    nlohmann::json cfg_json = nlohmann::json::object();
    cfg_json["name"] = "Debug " + cfg.project.name;
    cfg_json["type"] = dbg.type;
    cfg_json["request"] = "launch";
    cfg_json["program"] = "${workspaceFolder}/" + dbg.program;
    cfg_json["cwd"] = "${workspaceFolder}";
    cfg_json["externalConsole"] = false;
    cfg_json["preLaunchTask"] = "ezmk-build";   // key aligned with tasks.json
    if (dbg.type == "cppdbg") {
        cfg_json["miDebuggerPath"] = dbg.mi_debugger_path;
        cfg_json["setupCommands"] = nlohmann::json::array({
            nlohmann::json{{"description", "Enable pretty-printing for gdb"},
                           {"text", "-enable-pretty-printing"},
                           {"ignoreFailures", true}},
        });
    }
    launch["configurations"] = nlohmann::json::array({cfg_json});

    // ---- tasks.json (design §3.3) ----
    // Dependency include paths/macros are NOT hardcoded — `ezmk build` injects
    // them; the debug/index side gets them from settings/compile_commands.
    nlohmann::json tasks = nlohmann::json::object();
    tasks["version"] = "2.0.0";
    nlohmann::json task = nlohmann::json::object();
    task["label"] = "ezmk-build";
    task["type"] = "shell";
    task["command"] = "ezmk build";
    if (!profile.empty()) {
        task["args"] = nlohmann::json::array({"--profile", profile});
    }
    task["group"] = nlohmann::json{{"kind", "build"}, {"isDefault", true}};
    tasks["tasks"] = nlohmann::json::array({task});

    // ---- settings.json (design §3.4) ----
    // Prefer compile_commands.json (single source of truth); fall back to
    // C_Cpp.default.* only when no database exists / is configured.
    nlohmann::json settings = nlohmann::json::object();
    const bool has_db = cfg.compile.compile_commands ||
                        fs::exists(project_root / "compile_commands.json");
    if (has_db) {
        settings["clangd.arguments"] =
            nlohmann::json::array({"--compile-commands-dir=${workspaceFolder}"});
    } else {
        auto compile = effective_compile(cfg, profile);
        std::vector<std::string> include_dirs = compile.include_dirs;
        std::vector<std::string> defines;
        for (const auto& f : compile.flags) {
            if (f.rfind("-I", 0) == 0 && f.size() > 2) {
                include_dirs.push_back(f.substr(2));
            } else if (f.rfind("-D", 0) == 0 && f.size() > 2) {
                defines.push_back(f.substr(2));
            }
        }
        // ezmk standard macros + [compile].macros (same sources as export cmake).
        if (compile.ezmk_macros) {
            for (const auto& m : build::generate_ezmk_macros(cfg)) {
                if (m.rfind("-D", 0) == 0 && m.size() > 2) {
                    defines.push_back(m.substr(2));
                }
            }
        }
        for (const auto& [k, v] : compile.macros) {
            defines.push_back(v.empty() ? k : k + "=" + escape_macro_value(v));
        }

        nlohmann::json inc = nlohmann::json::array();
        for (const auto& d : include_dirs) {
            fs::path p = fs::path(d).is_absolute() ? fs::path(d) : (project_root / d);
            inc.push_back(fs::absolute(p).lexically_normal().generic_string());
        }
        // Installed dependency package include dirs (project → user → global).
        auto add_pkg_includes = [&](const std::vector<config::DependsEntry>& deps) {
            for (const auto& dep : deps) {
                fs::path pkg = find_installed_pkg(dep.name);
                if (!pkg.empty() && fs::exists(pkg / "include")) {
                    inc.push_back((pkg / "include").lexically_normal().generic_string());
                }
            }
        };
        add_pkg_includes(cfg.depends.libs);
        add_pkg_includes(cfg.depends.want);

        settings["C_Cpp.default.includePath"] = inc;
        settings["C_Cpp.default.defines"] = defines;
    }

    VscodeFiles out;
    out.launch = launch.dump(2) + "\n";
    out.tasks = tasks.dump(2) + "\n";
    out.settings = settings.dump(2) + "\n";
    return out;
}

int export_vscode(const config::EzConfig& cfg,
                  const fs::path& project_root,
                  const ExportOptions& opts) {    fs::path dir = project_root / ".vscode";
    VscodeFiles files = build_vscode_files(cfg, project_root, opts);

    struct NamedFile { const char* name; const std::string& text; };
    const NamedFile trio[] = {
        {"launch.json", files.launch},
        {"tasks.json", files.tasks},
        {"settings.json", files.settings},
    };

    // Overwrite safety: refuse unless --overwrite (design §3.1) — checked per
    // file so a partial existing trio is never half-replaced silently.
    if (!opts.overwrite) {
        for (const auto& f : trio) {
            if (fs::exists(dir / f.name)) {
                util::fatal(ezmk::i18n::I18nKey::export_exists_refuse,
                            {{"path", (dir / f.name).string()}});
            }
        }
    }

    std::error_code ec;
    fs::create_directories(dir, ec);
    if (ec) {
        util::fatal(std::string("failed to create .vscode/ directory: ") +
                    ec.message());
    }

    // Atomic write per file (temp → rename), mirroring export_cmake.
    for (const auto& f : trio) {
        fs::path out = dir / f.name;
        auto tmp = out;
        tmp += ".tmp";
        util::file_write(tmp, f.text);
        fs::rename(tmp, out, ec);
        if (ec) util::file_write(out, f.text);
        util::info(ezmk::i18n::I18nKey::export_written, {{"path", out.string()}});
    }
    return 0;
}

// 1.4.0-dev.4: CMake standard capability confirmation — see export.hpp.
// Conservative: an unparseable toolchain version (compiler_tag empty) skips
// the check entirely (the generated CMake may run on a different toolchain
// than the one detected at export time).
// 1.4.0-pre.1: C 侧按**序数**比较（年份不是单调序）——C89→0、C99→1、C11→2、
// C17→3，能力来自 max_supported_c_std（C17/C11）；旧的数值比较会把
// C_STANDARD 99 误报为超出 C++ 能力（99 > 23），C17 也用错了 C++ 能力表。
std::string std_capability_note(const std::string& std_kind, int std_ver,
                                const toolchain::Toolchain& tc) {
    if (std_ver <= 0) return "";
    if (toolchain::compiler_tag(tc).empty()) return "";  // 版本未知 → 不警告

    if (std_kind == "C") {
        // C 标准 → 序数；不在 {89,99,11,17}（如 C23）→ 能力表域外，不警告。
        auto c_ordinal = [](int ver) -> int {
            switch (ver) {
                case 89: return 0;
                case 99: return 1;
                case 11: return 2;
                case 17: return 3;
                default: return -1;
            }
        };
        int decl_ord = c_ordinal(std_ver);
        if (decl_ord < 0) return "";
        const std::string cap = toolchain::max_supported_c_std(tc.family, tc.version);
        int cap_ver = 0;
        try {
            if (cap.size() > 1) cap_ver = std::stoi(cap.substr(1));  // "C17" → 17
        } catch (...) {}
        int cap_ord = c_ordinal(cap_ver);
        if (cap_ord < 0) return "";  // 未知 cap → 保守不警告
        if (decl_ord > cap_ord) {
            return "# " + std_kind + "_STANDARD " + std::to_string(std_ver) +
                   " exceeds the target toolchain capability (" + cap + ")";
        }
        return "";
    }

    // C++ 侧（std_kind == "CXX" 等）：保持 dev.4 原逻辑不变。
    const std::string cap = toolchain::max_supported_std(tc.family, tc.version);
    int cap_ver = 0;
    try {
        if (cap.size() > 3) cap_ver = std::stoi(cap.substr(3));
    } catch (...) {}
    if (cap_ver > 0 && std_ver > cap_ver) {
        return "# " + std_kind + "_STANDARD " + std::to_string(std_ver) +
               " exceeds the target toolchain capability (" + cap + ")";
    }
    return "";
}

} // namespace ezmk::export_gen
