#include "ezmk/lockfile.hpp"
#include "ezmk/crypto.hpp"
#include "ezmk/i18n.hpp"
#include "ezmk/pkg.hpp"
#include "ezmk/util.hpp"
#include "toml.hpp"

#include <algorithm>
#include <set>
#include <sstream>
#include <stdexcept>

namespace ezmk::lockfile {

// ===================================================================
// Lockfile path
// ===================================================================

static fs::path lockfile_path(const fs::path& proj_root) {
    return proj_root / "ezmk.lock";
}

// ===================================================================
// Load / Save
// ===================================================================

std::optional<config::Lockfile> load(const fs::path& proj_root) {
    auto path = lockfile_path(proj_root);
    if (!util::file_exists(path)) return std::nullopt;

    try {
        auto root = toml::parse_file(path.string());
        config::Lockfile lf;

        // [metadata]
        auto meta = root["metadata"].as_table();
        if (meta) {
            lf.version = (*meta)["version"].value_or(1);
            lf.generated_by = (*meta)["generated_by"].value_or("");
            lf.generated_at = (*meta)["generated_at"].value_or("");
            lf.toolchain = (*meta)["toolchain"].value_or("");
            lf.toolchain_version = (*meta)["toolchain_version"].value_or("");
            // 1.1.2 C3: direct deps (absent in pre-1.1.2 lockfiles → empty)
            auto dd = (*meta)["direct_deps"].as_array();
            if (dd) {
                for (size_t i = 0; i < dd->size(); ++i) {
                    if (auto v = (*dd)[i].value<std::string>()) {
                        lf.direct_deps.push_back(*v);
                    }
                }
            }
        }

        // [[packages]]
        auto pkgs = root["packages"].as_array();
        if (pkgs) {
            for (size_t i = 0; i < pkgs->size(); ++i) {
                auto tbl = (*pkgs)[i].as_table();
                if (!tbl) continue;

                config::LockedPackage pkg;
                pkg.name = (*tbl)["name"].value_or("");
                pkg.version = (*tbl)["version"].value_or("");
                pkg.source = (*tbl)["source"].value_or("");
                pkg.source_url = (*tbl)["source_url"].value_or("");
                pkg.sha256 = (*tbl)["sha256"].value_or("");
                pkg.type = (*tbl)["type"].value_or("static");
                pkg.scope = (*tbl)["scope"].value_or("user");
                pkg.platform = (*tbl)["platform"].value_or("");

                auto deps = (*tbl)["dependencies"].as_array();
                if (deps) {
                    for (size_t j = 0; j < deps->size(); ++j) {
                        if (auto v = (*deps)[j].value<std::string>()) {
                            pkg.dependencies.push_back(*v);
                        }
                    }
                }

                if (!pkg.name.empty()) {
                    lf.packages.push_back(std::move(pkg));
                }
            }
        }

        return lf;
    } catch (const std::exception& e) {
        util::warn(std::string("failed to parse ezmk.lock: ") + e.what());
        return std::nullopt;
    }
}

void save(const fs::path& proj_root, const config::Lockfile& lf) {
    auto path = lockfile_path(proj_root);

    std::ostringstream out;

    out << "# ezmk.lock — AUTO-GENERATED by ezmk. Do not edit manually.\n";
    out << "# Generated by: " << lf.generated_by << "\n\n";

    out << "[metadata]\n";
    out << "version = " << lf.version << "\n";
    out << "generated_by = " << util::toml_quote(lf.generated_by) << "\n";
    out << "generated_at = " << util::toml_quote(lf.generated_at) << "\n";
    out << "toolchain = " << util::toml_quote(lf.toolchain) << "\n";
    out << "toolchain_version = " << util::toml_quote(lf.toolchain_version) << "\n";
    // 1.1.2 C3: root project's direct deps (name or name@spec), sorted
    out << "direct_deps = [";
    for (size_t i = 0; i < lf.direct_deps.size(); ++i) {
        if (i > 0) out << ", ";
        out << util::toml_quote(lf.direct_deps[i]);
    }
    out << "]\n\n";

    // 1.1.2 C5: package name/version/url are user-controlled — toml_quote all
    // interpolated strings so a `"` or newline cannot corrupt/inject ezmk.lock.
    for (auto& pkg : lf.packages) {
        out << "[[packages]]\n";
        out << "name = " << util::toml_quote(pkg.name) << "\n";
        out << "version = " << util::toml_quote(pkg.version) << "\n";
        out << "source = " << util::toml_quote(pkg.source) << "\n";
        out << "source_url = " << util::toml_quote(pkg.source_url) << "\n";
        out << "sha256 = " << util::toml_quote(pkg.sha256) << "\n";
        out << "type = " << util::toml_quote(pkg.type) << "\n";
        out << "scope = " << util::toml_quote(pkg.scope) << "\n";
        out << "platform = " << util::toml_quote(pkg.platform) << "\n";
        if (!pkg.dependencies.empty()) {
            out << "dependencies = [";
            for (size_t i = 0; i < pkg.dependencies.size(); ++i) {
                if (i > 0) out << ", ";
                out << util::toml_quote(pkg.dependencies[i]);
            }
            out << "]\n";
        } else {
            out << "dependencies = []\n";
        }
        out << "\n";
    }

    util::file_write(path, out.str());
}

// ===================================================================
// Verify
// ===================================================================

std::vector<std::string> verify(const fs::path& proj_root,
                                const config::Lockfile& lf) {
    std::vector<std::string> mismatches;

    for (auto& pkg : lf.packages) {
        // 1.1.3 S2: lockfile 不可信，包名先校验再拼路径（防路径穿越）
        util::validate_pkg_name(pkg.name);
        // Determine package install path based on scope
        fs::path pkg_path;
        if (pkg.scope == "project") {
            pkg_path = proj_root / ".ezmk/pkg" / pkg.name;
        } else if (pkg.scope == "user") {
#ifdef EZMK_WIN
            const char* appdata = std::getenv("LOCALAPPDATA");
            if (appdata) pkg_path = fs::path(appdata) / "ezmk/pkg" / pkg.name;
            else pkg_path = util::get_home_dir() / "AppData/Local/ezmk/pkg" / pkg.name;
#else
            pkg_path = util::get_home_dir() / ".local/ezmk/pkg" / pkg.name;
#endif
        } else { // global
            pkg_path = util::get_exe_dir() / "pkg" / pkg.name;
        }

        if (!util::file_exists(pkg_path)) {
            mismatches.push_back(pkg.name);
            continue;
        }

        // For header-only packages, hash the entire include/ directory
        // For static/shared, hash the .a/.lib file
        if (pkg.type == "header-only") {
            // Skip sha256 check for header-only (include/ content is verified via install)
            continue;
        }

        fs::path lib_file;
        auto build_dir = pkg_path / "build";
        if (util::file_exists(build_dir)) {
            for (auto& e : fs::directory_iterator(build_dir)) {
                auto ext = e.path().extension().string();
                if (ext == ".a" || ext == ".lib") {
                    lib_file = e.path();
                    break;
                }
            }
        }

        if (!lib_file.empty() && !pkg.sha256.empty()) {
            std::string actual = crypto::sha256_file(lib_file);
            if (actual != pkg.sha256) {
                mismatches.push_back(pkg.name);
            }
        }
    }

    return mismatches;
}

// ===================================================================
// Depends changed detection
// ===================================================================

std::vector<std::string> direct_dep_specs(const config::EzConfig& cfg) {
    std::vector<std::string> specs;
    auto push = [&](const config::DependsEntry& d) {
        // user syntax: "pkg" | "pkg@1.2" | "pkg@^1.2" | "pkg@~1.2" | "pkg@>=1.2" ...
        std::string s = d.name;
        if (d.constraint.op != config::VersionConstraint::None) {
            s += "@";
            switch (d.constraint.op) {
                case config::VersionConstraint::Exact:     break;   // "name@1.2"
                case config::VersionConstraint::Compatible: s += "^"; break;
                case config::VersionConstraint::Approx:    s += "~";  break;
                case config::VersionConstraint::Gte:       s += ">="; break;
                case config::VersionConstraint::Gt:        s += ">";  break;
                default: break;
            }
            s += d.constraint.version;
        }
        specs.push_back(std::move(s));
    };
    for (auto& d : cfg.depends.libs) push(d);
    for (auto& d : cfg.depends.want) push(d);
    std::sort(specs.begin(), specs.end());
    return specs;
}

bool depends_changed(const config::EzConfig& cfg,
                     const config::Lockfile& lf) {
    // 1.1.2 C3: compare DIRECT deps (with constraints), not cfg deps vs ALL
    // lockfile packages. packages[] includes transitive/auto-installed deps, so
    // the old name-set comparison was always "changed" whenever there was any
    // transitive dep — making --locked always fatal even when nothing changed.
    // NOTE: bind the vector — the set ctor must use one object's begin/end pair
    // (two separate temporaries would be undefined behavior).
    auto cfg_vec = direct_dep_specs(cfg);
    std::set<std::string> cfg_deps(cfg_vec.begin(), cfg_vec.end());
    std::set<std::string> lock_deps(lf.direct_deps.begin(), lf.direct_deps.end());

    if (cfg_deps != lock_deps) return true;

    // Backward compat: a pre-1.1.2 lockfile has no direct_deps field. If the
    // project declares deps, treat as changed so the lockfile regenerates.
    if (lf.direct_deps.empty() && !lf.packages.empty() && !cfg_deps.empty()) return true;

    return false;
}

} // namespace ezmk::lockfile
