#include "ezmk/lockfile.hpp"
#include "ezmk/crypto.hpp"
#include "ezmk/i18n.hpp"
#include "ezmk/pkg.hpp"
#include "ezmk/util.hpp"
#include "toml.hpp"

#include <set>
#include <sstream>
#include <stdexcept>

namespace ezmk::lockfile {

// ===================================================================
// Lockfile path
// ===================================================================

static fs::path lockfile_path(const fs::path& proj_root) {
    return proj_root / "ezmk.lock";
}

// ===================================================================
// Load / Save
// ===================================================================

std::optional<config::Lockfile> load(const fs::path& proj_root) {
    auto path = lockfile_path(proj_root);
    if (!util::file_exists(path)) return std::nullopt;

    try {
        auto root = toml::parse_file(path.string());
        config::Lockfile lf;

        // [metadata]
        auto meta = root["metadata"].as_table();
        if (meta) {
            lf.version = (*meta)["version"].value_or(1);
            lf.generated_by = (*meta)["generated_by"].value_or("");
            lf.generated_at = (*meta)["generated_at"].value_or("");
            lf.toolchain = (*meta)["toolchain"].value_or("");
            lf.toolchain_version = (*meta)["toolchain_version"].value_or("");
        }

        // [[packages]]
        auto pkgs = root["packages"].as_array();
        if (pkgs) {
            for (size_t i = 0; i < pkgs->size(); ++i) {
                auto tbl = (*pkgs)[i].as_table();
                if (!tbl) continue;

                config::LockedPackage pkg;
                pkg.name = (*tbl)["name"].value_or("");
                pkg.version = (*tbl)["version"].value_or("");
                pkg.source = (*tbl)["source"].value_or("");
                pkg.source_url = (*tbl)["source_url"].value_or("");
                pkg.sha256 = (*tbl)["sha256"].value_or("");
                pkg.type = (*tbl)["type"].value_or("static");
                pkg.scope = (*tbl)["scope"].value_or("user");
                pkg.platform = (*tbl)["platform"].value_or("");

                auto deps = (*tbl)["dependencies"].as_array();
                if (deps) {
                    for (size_t j = 0; j < deps->size(); ++j) {
                        if (auto v = (*deps)[j].value<std::string>()) {
                            pkg.dependencies.push_back(*v);
                        }
                    }
                }

                if (!pkg.name.empty()) {
                    lf.packages.push_back(std::move(pkg));
                }
            }
        }

        return lf;
    } catch (const std::exception& e) {
        util::warn(std::string("failed to parse ezmk.lock: ") + e.what());
        return std::nullopt;
    }
}

void save(const fs::path& proj_root, const config::Lockfile& lf) {
    auto path = lockfile_path(proj_root);

    std::ostringstream out;

    out << "# ezmk.lock — AUTO-GENERATED by ezmk. Do not edit manually.\n";
    out << "# Generated by: " << lf.generated_by << "\n\n";

    out << "[metadata]\n";
    out << "version = " << lf.version << "\n";
    out << "generated_by = \"" << lf.generated_by << "\"\n";
    out << "generated_at = \"" << lf.generated_at << "\"\n";
    out << "toolchain = \"" << lf.toolchain << "\"\n";
    out << "toolchain_version = \"" << lf.toolchain_version << "\"\n\n";

    for (auto& pkg : lf.packages) {
        out << "[[packages]]\n";
        out << "name = \"" << pkg.name << "\"\n";
        out << "version = \"" << pkg.version << "\"\n";
        out << "source = \"" << pkg.source << "\"\n";
        out << "source_url = \"" << pkg.source_url << "\"\n";
        out << "sha256 = \"" << pkg.sha256 << "\"\n";
        out << "type = \"" << pkg.type << "\"\n";
        out << "scope = \"" << pkg.scope << "\"\n";
        out << "platform = \"" << pkg.platform << "\"\n";
        if (!pkg.dependencies.empty()) {
            out << "dependencies = [";
            for (size_t i = 0; i < pkg.dependencies.size(); ++i) {
                if (i > 0) out << ", ";
                out << "\"" << pkg.dependencies[i] << "\"";
            }
            out << "]\n";
        } else {
            out << "dependencies = []\n";
        }
        out << "\n";
    }

    util::file_write(path, out.str());
}

// ===================================================================
// Verify
// ===================================================================

std::vector<std::string> verify(const fs::path& proj_root,
                                const config::Lockfile& lf) {
    std::vector<std::string> mismatches;

    for (auto& pkg : lf.packages) {
        // Determine package install path based on scope
        fs::path pkg_path;
        if (pkg.scope == "project") {
            pkg_path = proj_root / ".ezmk/pkg" / pkg.name;
        } else if (pkg.scope == "user") {
#ifdef EZMK_WIN
            const char* appdata = std::getenv("LOCALAPPDATA");
            if (appdata) pkg_path = fs::path(appdata) / "ezmk/pkg" / pkg.name;
            else pkg_path = util::get_home_dir() / "AppData/Local/ezmk/pkg" / pkg.name;
#else
            pkg_path = util::get_home_dir() / ".local/ezmk/pkg" / pkg.name;
#endif
        } else { // global
            pkg_path = util::get_exe_dir() / "pkg" / pkg.name;
        }

        if (!util::file_exists(pkg_path)) {
            mismatches.push_back(pkg.name);
            continue;
        }

        // For header-only packages, hash the entire include/ directory
        // For static/shared, hash the .a/.lib file
        if (pkg.type == "header-only") {
            // Skip sha256 check for header-only (include/ content is verified via install)
            continue;
        }

        fs::path lib_file;
        auto build_dir = pkg_path / "build";
        if (util::file_exists(build_dir)) {
            for (auto& e : fs::directory_iterator(build_dir)) {
                auto ext = e.path().extension().string();
                if (ext == ".a" || ext == ".lib") {
                    lib_file = e.path();
                    break;
                }
            }
        }

        if (!lib_file.empty() && !pkg.sha256.empty()) {
            std::string actual = crypto::sha256_file(lib_file);
            if (actual != pkg.sha256) {
                mismatches.push_back(pkg.name);
            }
        }
    }

    return mismatches;
}

// ===================================================================
// Depends changed detection
// ===================================================================

bool depends_changed(const config::EzConfig& cfg,
                     const config::Lockfile& lf) {
    // Collect dependency names from ezmk.toml
    std::set<std::string> cfg_deps;
    for (auto& d : cfg.depends.libs) cfg_deps.insert(d.name);
    for (auto& d : cfg.depends.want) cfg_deps.insert(d.name);

    // Collect dependency names from lockfile
    std::set<std::string> lock_deps;
    for (auto& p : lf.packages) lock_deps.insert(p.name);

    return cfg_deps != lock_deps;
}

} // namespace ezmk::lockfile
