#include "ezmk/cli.hpp"
#include "ezmk/config.hpp"
#include "ezmk/project.hpp"
#include "ezmk/build.hpp"
#include "ezmk/cache.hpp"
#include "ezmk/compile_db.hpp"
#include "ezmk/export.hpp"
#include "ezmk/import.hpp"
#include "ezmk/pkg.hpp"
#include "ezmk/repo.hpp"
#include "ezmk/util.hpp"
#include "ezmk/i18n.hpp"
#include "ezmk/lua_api.hpp"
#include "ezmk/file_watcher.hpp"
#include "ezmk/example.hpp"      // 1.2.3: ezmk example
#include "ezmk/workspace.hpp"    // 1.3.0-dev.1
#include "ezmk/workspace_build.hpp"  // 1.3.0-dev.2: ezmk workspace commands
#include "ezmk/version.hpp"   // generated by build.sh
#include "ezmk/logo.gen.h"     // 0.9.6+: generated by embed_logo.py

#include <atomic>
#include <csignal>
#include <exception>
#include <filesystem>
#include <iostream>
#include <thread>

// 0.2.5+: Auto-update repos helper — shared by build/run/watch commands.
static void auto_update_repos(const ezmk::cli::BuildOptions& opts) {
    if (opts.auto_update) {
        ezmk::util::info(ezmk::i18n::I18nKey::auto_updating_repos);
        ezmk::repo::update("", {ezmk::cli::Scope::Project,
                                 ezmk::cli::Scope::User,
                                 ezmk::cli::Scope::Global});
    }
}

// 1.2.0-dev.7: Locate the project root for commands that require an ezmk.toml
// (upward search, max 5 levels). A missing config is a fatal error with a clear
// message pointing at the search boundary.
static std::filesystem::path require_project_root() {
    auto root = ezmk::util::locate_project_root(std::filesystem::current_path());
    if (!root.has_value()) {
        ezmk::util::fatal(ezmk::i18n::get(ezmk::i18n::I18nKey::config_not_found_upward));
    }
    return *root;
}

// 1.3.6: shared executable launcher — the "running" message, argument assembly,
// blocking run and stdout/stderr echo used by BOTH `project run` and
// `watch --run` (previously duplicated in two places).
// warn_on_nonzero=false → returns the child's exit code (run semantics);
// warn_on_nonzero=true  → warns on non-zero and returns 0 (watch keeps looping).
static int run_executable(const std::filesystem::path& exe,
                          const std::vector<std::string>& args,
                          bool warn_on_nonzero) {
    ezmk::util::info(ezmk::i18n::I18nKey::running,
                     {{"exe", exe.filename().string()}});
    std::string cmd = "\"" + exe.string() + "\"";
    for (const auto& a : args) {
        cmd += " \"" + ezmk::util::escape_shell_arg(a) + "\"";
    }
    auto res = ezmk::util::run_command(cmd);
    if (!res.out.empty()) std::cout << res.out;
    if (!res.err.empty()) std::cerr << res.err;
    if (res.exit_code != 0 && warn_on_nonzero) {
        ezmk::util::warn(ezmk::i18n::fmt(
            ezmk::i18n::I18nKey::watch_run_exit_nonzero,
            {{"exe", exe.filename().string()},
             {"code", std::to_string(res.exit_code)}}));
        return 0;
    }
    return res.exit_code;
}

// 1.3.0-dev.2: load the workspace from the current directory or fail with a
// clear "no workspace found" error (shared by all `ezmk workspace` commands).
static ezmk::workspace::Workspace require_workspace() {
    auto ws = ezmk::workspace::load_from(std::filesystem::current_path());
    if (!ws) {
        ezmk::util::fatal(
            ezmk::i18n::fmt(ezmk::i18n::I18nKey::workspace_not_found,
                            {{"dir", std::filesystem::current_path().string()}}));
    }
    return *ws;
}

// 1.3.0-dev.2: `ezmk build` in a pure workspace container root (has
// ezmk-workspace.toml but no ezmk.toml) — hint at the workspace command
// instead of the generic "config not found" error.
static bool maybe_hint_pure_container() {
    auto proj = ezmk::util::locate_project_root(std::filesystem::current_path());
    if (proj) return false;
    auto ws_root = ezmk::workspace::locate_workspace_root(std::filesystem::current_path());
    if (!ws_root) return false;
    ezmk::util::fatal(ezmk::i18n::get(ezmk::i18n::I18nKey::workspace_err_pure_container));
    return true;  // unreachable
}

// 1.2.0: shared compile_commands generation entry — used by both the
// `ezmk project cc` command and the (deprecated) `ezmk utils cc` redirect,
// so the two entry points always produce identical output.
static void generate_compile_db_entry(const std::string& output_path,
                                      const std::string& profile) {
    auto proj_root = require_project_root();
    auto cfg = ezmk::config::parse_config((proj_root / "ezmk.toml").string());
    ezmk::cli::BuildOptions opts;
    opts.profile = profile;
    // 1.2.0-dev.3: no --profile → fall back to [compile].default_profile (if set)
    if (opts.profile.empty()) opts.profile = cfg.compile.default_profile;

    std::filesystem::path out;
    if (!output_path.empty()) {
        out = output_path;
        if (out.is_relative()) out = proj_root / out;
    }

    ezmk::compile_db::generate_compile_db(cfg, opts, proj_root, out);
}

// 1.1.1: Built-in `cc` tool — generates compile_commands.json via the C++
// compile_db generator (drift-free). Intercepts `ezmk utils cc` before the
// Lua script lookup; the Lua cc.lua is no longer executed.
// 1.2.0: `ezmk utils cc` is deprecated — emits a warning, then redirects to
// the shared project-cc entry. The tool stays functional until 2.0.0.
static int run_builtin_cc(const std::vector<std::string>& utils_args) {
    ezmk::util::warn(ezmk::i18n::I18nKey::utils_cc_deprecated);

    std::string output_path;
    std::string profile;
    bool show_help = false;

    for (size_t i = 0; i < utils_args.size(); ++i) {
        const auto& a = utils_args[i];
        if (a == "-h" || a == "--help") {
            show_help = true;
        } else if (a == "-o" || a == "--output") {
            if (i + 1 >= utils_args.size()) {
                ezmk::util::fatal(std::string("option '") + a +
                                  "' for 'ezmk utils cc' requires a value");
            }
            output_path = utils_args[++i];
        } else if (a.rfind("--output=", 0) == 0) {
            output_path = a.substr(9);
        } else if (a == "--profile") {
            if (i + 1 >= utils_args.size()) {
                ezmk::util::fatal(std::string("option '") + a +
                                  "' for 'ezmk utils cc' requires a value");
            }
            profile = utils_args[++i];
        } else if (a.rfind("--profile=", 0) == 0) {
            profile = a.substr(10);
        } else {
            ezmk::util::fatal(std::string("unknown option for 'ezmk utils cc': ") + a);
        }
    }

    if (show_help) {
        std::cout << ezmk::i18n::get(ezmk::i18n::I18nKey::cc_help) << "\n";
        return 0;
    }

    generate_compile_db_entry(output_path, profile);
    return 0;
}

namespace fs = std::filesystem;

int main(int argc, char** argv) {
    ezmk::util::init_console();
    ezmk::i18n::init();  // detect language, load locale data
    ezmk::lua::init();   // initialize Lua interpreter

    try {
        auto args = ezmk::cli::parse(argc, argv);

        // 0.9.8+: show shorthand expansion hint in verbose mode
        if (!args.shorthand_expansion.empty()) {
            ezmk::util::info_line(ezmk::i18n::fmt(ezmk::i18n::I18nKey::shorthand_expansion,
                                                  {{"mapping", args.shorthand_expansion}}));
        }

        switch (args.cmd) {

        case ezmk::cli::Command::Help: {
            // 0.9.6+: Show ASCII logo (with color when available)
            if (ezmk::EZMK_LOGO[0] != '\0') {
                bool use_color = ezmk::util::supports_color();
                if (use_color) {
                    std::cout << "\033[36m" << ezmk::EZMK_LOGO << "\033[0m\n";
                } else {
                    std::cout << ezmk::EZMK_LOGO << "\n";
                }
                // Show version below logo
                std::cout << ezmk::i18n::fmt(ezmk::i18n::I18nKey::version_output,
                                             {{"version", EZMK_VERSION}}) << "\n\n";
            }
            ezmk::cli::print_usage();
            break;
        }

        case ezmk::cli::Command::ProjectNew:
            ezmk::project::create_project(*args.project_name, args.project_type,
                                          args.disable_git_init, args.disable_gitignore);
            break;

        case ezmk::cli::Command::Version:
            std::cout << ezmk::i18n::fmt(ezmk::i18n::I18nKey::version_output,
                                         {{"version", EZMK_VERSION}}) << std::endl;
            break;

        case ezmk::cli::Command::ProjectBuild: {
            maybe_hint_pure_container();   // 1.3.0-dev.2
            auto_update_repos(args.build_opts);
            auto proj_root = require_project_root();
            auto cfg = ezmk::config::parse_config((proj_root / "ezmk.toml").string());
            ezmk::build::build_project(cfg, args.build_opts);
            break;
        }

        case ezmk::cli::Command::ProjectRun: {
            auto_update_repos(args.build_opts);
            auto proj_root = require_project_root();
            auto cfg = ezmk::config::parse_config((proj_root / "ezmk.toml").string());
            auto exe = ezmk::build::build_project(cfg, args.build_opts);
            // 1.3.6: shared launcher — forwards positional args (after "--")
            // to the program and returns the child's exit code.
            int rc = run_executable(exe, args.program_args, /*warn_on_nonzero=*/false);
            if (rc != 0) {
                return rc;
            }
            break;
        }

        case ezmk::cli::Command::ProjectClean: {
            // 1.2.0-dev.7: clean operates on the located project root
            // (fall back to CWD when no ezmk.toml — cleaning is safe regardless)
            auto proj_root = ezmk::util::locate_project_root(fs::current_path())
                                .value_or(fs::current_path());
            ezmk::cache::clear_cache();
            { std::error_code ec; fs::remove_all(proj_root / ".ezmk/temp", ec); }  // best-effort
            ezmk::util::info(ezmk::i18n::I18nKey::cleaned);
            break;
        }

        // 1.1.0: project install
        case ezmk::cli::Command::ProjectInstall: {
            auto proj_root = require_project_root();
            auto cfg = ezmk::config::parse_config((proj_root / "ezmk.toml").string());
            auto& install_opts = *args.project_install_opts;

            // 1.2.0-dev.11: the install -v flag used to only mark the install
            // step — propagate it to the build phase so `ezmk install -v` shows
            // the compile commands too.
            if (install_opts.verbose) {
                args.build_opts.verbose = true;
            }

            // Build first
            ezmk::build::build_project(cfg, args.build_opts);

            // Install
            ezmk::build::install_project(cfg, install_opts, proj_root);
            break;
        }

        case ezmk::cli::Command::ProjectPack: {
            auto proj_root = require_project_root();
            auto cfg = ezmk::config::parse_config((proj_root / "ezmk.toml").string());

            ezmk::build::pack_project(cfg, *args.project_pack_opts, proj_root);
            break;
        }

        // 1.2.0: project cc — formal compile_commands generation command
        case ezmk::cli::Command::ProjectCc: {
            const auto& opts = *args.project_cc_opts;
            generate_compile_db_entry(opts.output, opts.profile);
            break;
        }

        // 1.2.0: project export cmake — one-shot CMakeLists.txt generation
        // 1.4.0-dev.1: + vscode — .vscode/ debug config trio
        case ezmk::cli::Command::ProjectExport: {
            auto proj_root = require_project_root();
            auto cfg = ezmk::config::parse_config((proj_root / "ezmk.toml").string());
            const auto& eo = *args.project_export_opts;
            ezmk::export_gen::ExportOptions eo2;
            eo2.output = eo.output;
            eo2.overwrite = eo.overwrite;
            eo2.profile = eo.profile;
            eo2.resolve = eo.resolve;
            eo2.use_glob = eo.use_glob;
            if (eo.target == "vscode") {
                ezmk::export_gen::export_vscode(cfg, proj_root, eo2);
            } else {
                ezmk::export_gen::export_cmake(cfg, proj_root, eo2);
            }
            break;
        }

        // 1.2.0: project import — import a CMake project into ezmk.toml
        case ezmk::cli::Command::ProjectImport: {
            const auto& io = *args.project_import_opts;
            ezmk::import::import_project(io, std::filesystem::current_path());
            break;
        }

        // 1.1.0-dev.6: project test
        case ezmk::cli::Command::ProjectTest: {
            // 1.2.0-dev.11: removed the dead auto_update_repos(args.build_opts)
            // call — `ezmk test` never fills build_opts, so it always ran with
            // defaults (a no-op).
            auto proj_root = require_project_root();
            auto cfg = ezmk::config::parse_config((proj_root / "ezmk.toml").string());
            ezmk::build::run_tests(cfg,
                                    args.test_framework,
                                    args.test_filter,
                                    args.test_verbose,
                                    args.test_profile,
                                    args.test_report);
            break;
        }

        case ezmk::cli::Command::ProjectWatch: {
            // 0.2.3+: Watch mode — file monitoring + auto rebuild
            auto_update_repos(args.build_opts);
            auto proj_root = require_project_root();
            auto cfg = ezmk::config::parse_config((proj_root / "ezmk.toml").string());

            // 1.3.4: --run only makes sense for executable projects — reject
            // static/shared/utils at startup (config-time gate, 坑 3).
            if (args.watch_run && cfg.project.type != "executable") {
                ezmk::util::fatal(
                    ezmk::i18n::fmt(ezmk::i18n::I18nKey::cli_err_run_needs_executable,
                                    {{"type", cfg.project.type}}));
            }

            // SIGINT handler for graceful exit
            static std::atomic<bool> sigint_received{false};
            auto prev_handler = std::signal(SIGINT, [](int) {
                sigint_received = true;
            });

            // 1.3.4: run the freshly-built executable after a SUCCESSFUL
            // rebuild. The blocking run happens on the watcher thread — change
            // detection is naturally paused while the program runs, and watch
            // resumes when it exits (zero process management). Non-zero exit →
            // warn, keep watching (watch is a loop, not a one-shot run).
            auto run_watched_exe = [&](const std::filesystem::path& exe) {
                if (!args.watch_run || exe.empty()) return;
                // 1.3.6: shared launcher — warn_on_nonzero=true keeps watch
                // looping after a non-zero child exit (watch is a loop).
                run_executable(exe, {}, /*warn_on_nonzero=*/true);
            };

            // Initial build (unless --no-build-on-start)
            if (!args.watch_no_build_on_start) {
                try {
                    ezmk::build::build_project(cfg, args.build_opts);
                    ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                } catch (const std::exception& e) {
                    ezmk::util::error(std::string("initial build failed: ") + e.what());
                    ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                }
            } else {
                ezmk::util::info(ezmk::i18n::I18nKey::watch_skip_initial);
            }

            // Collect directories to watch.
            // 1.2.0-dev.11: the profile merge was dead code here — profile
            // merge only changes flags/macros, never src_dirs/include_dirs, so
            // it had no effect on the watch set (and silently ignored unknown
            // profiles). Watch the base config's directories.
            std::vector<std::string> watch_dirs;
            // Use absolute path to ezmk.toml so parent_path() resolves correctly
            watch_dirs.push_back((proj_root / "ezmk.toml").string());
            for (auto& d : cfg.compile.src_dirs) {
                std::filesystem::path dir = d;
                if (dir.is_relative()) dir = proj_root / dir;
                if (std::filesystem::exists(dir)) watch_dirs.push_back(dir.string());
            }
            for (auto& d : cfg.compile.include_dirs) {
                std::filesystem::path dir = d;
                if (dir.is_relative()) dir = proj_root / dir;
                if (std::filesystem::exists(dir)) watch_dirs.push_back(dir.string());
            }

            // Create file watcher
            auto ezmk_toml_abs = std::filesystem::absolute(proj_root / "ezmk.toml").string();
            ezmk::util::FileWatcher watcher(
                [&](const std::filesystem::path& changed) {
                    auto changed_abs = std::filesystem::absolute(changed).string();
                    auto changed_name = changed.filename().string();

                    // Check if ezmk.toml changed → re-parse config, clear cache, full rebuild
                    if (changed_abs == ezmk_toml_abs || changed_name == "ezmk.toml") {
                        ezmk::util::info(ezmk::i18n::I18nKey::watch_config_changed);
                        ezmk::cache::clear_cache();
                        try {
                            auto new_cfg = ezmk::config::parse_config((proj_root / "ezmk.toml").string());
                            // 1.3.4: capture the exe and run it on success (坑 4: never run on failure).
                            auto exe = ezmk::build::build_project(new_cfg, args.build_opts);
                            run_watched_exe(exe);
                            ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                        } catch (const std::exception& e) {
                            ezmk::util::error(std::string("build failed: ") + e.what());
                            ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                        }
                        return;
                    }

                    // Source/header change → incremental build
                    ezmk::util::info(ezmk::i18n::I18nKey::watch_detected_change,
                                     {{"path", changed_abs}});
                    try {
                        auto cur_cfg = ezmk::config::parse_config((proj_root / "ezmk.toml").string());
                        // 1.3.4: capture the exe and run it on success (坑 4).
                        auto exe = ezmk::build::build_project(cur_cfg, args.build_opts);
                        run_watched_exe(exe);
                        ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                    } catch (const std::exception& e) {
                        ezmk::util::error(std::string("build failed: ") + e.what());
                        ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                    }
                },
                300  // 300ms debounce
            );

            // Add directories to watcher
            for (auto& d : watch_dirs) {
                std::filesystem::path dp(d);
                if (dp.filename() == "ezmk.toml") {
                    // Watch the parent directory of ezmk.toml non-recursively
                    watcher.add_directory(dp.parent_path(), /*recursive=*/false);
                } else {
                    watcher.add_directory(dp, /*recursive=*/true);
                }
            }

            // Run watcher in background thread, main thread waits for SIGINT
            std::thread watcher_thread([&watcher]() {
                watcher.run();
            });

            // Wait for SIGINT
            while (!sigint_received) {
                std::this_thread::sleep_for(std::chrono::milliseconds(200));
            }

            ezmk::util::info(ezmk::i18n::I18nKey::watch_stopping);
            watcher.stop();
            if (watcher_thread.joinable()) watcher_thread.join();

            // Restore previous handler
            std::signal(SIGINT, prev_handler);
            break;
        }

        case ezmk::cli::Command::PkgInstall: {
            auto& opts = *args.install_opts;
            ezmk::pkg::install(opts.pkg_file, opts.scope, opts.sha256, opts.assume_yes,
                                opts.locked, opts.no_lock);
            break;
        }

        case ezmk::cli::Command::PkgRemove: {
            auto& opts = *args.query_opts;
            ezmk::pkg::remove(opts.pkg_name, opts.scopes);
            break;
        }

        case ezmk::cli::Command::PkgSearch: {
            auto& opts = *args.query_opts;
            auto results = ezmk::pkg::search(opts.pkg_name, opts.scopes);
            if (results.empty()) {
                ezmk::util::info(ezmk::i18n::I18nKey::not_found,
                                 {{"pkg", opts.pkg_name}});
            } else {
                for (auto& p : results) {
                    std::cout << p.string() << "\n";
                }
            }
            break;
        }

        case ezmk::cli::Command::PkgInfo: {
            auto& opts = *args.query_opts;
            ezmk::pkg::info(opts.pkg_name, opts.scopes);
            break;
        }

        case ezmk::cli::Command::PkgList: {
            // 0.2.3+ — implementation in Phase 5
            auto& opts = *args.query_opts;
            ezmk::pkg::list(opts.scopes);
            break;
        }

        case ezmk::cli::Command::PkgUpdate: {
            auto& opts = *args.query_opts;
            if (opts.update_all) {
                ezmk::pkg::update_all(opts.scopes);
            } else {
                ezmk::pkg::update(opts.pkg_name, opts.scopes);
            }
            break;
        }

        case ezmk::cli::Command::RepoAdd:
            ezmk::repo::add(args.repo_opts);
            break;

        case ezmk::cli::Command::RepoRemove:
            ezmk::repo::remove(args.repo_opts.name, args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::RepoUpdate:
            ezmk::repo::update(args.repo_opts.name, args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::RepoList:
            ezmk::repo::list(args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::RepoInfo:   // 0.2.5+
            ezmk::repo::info(args.repo_opts.name, args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::Example: {   // 1.2.3
            const auto& opts = args.example_opts.value();
            if (opts.list) {
                ezmk::example::list_examples();
            } else {
                ezmk::example::create_example(opts.name, opts.output_dir);
            }
            break;
        }

        // 1.3.0-dev.2: `ezmk workspace` command group
        case ezmk::cli::Command::WorkspaceList: {
            ezmk::workspace_build::list_workspace(require_workspace());
            break;
        }

        case ezmk::cli::Command::WorkspaceBuild: {
            auto ws = require_workspace();
            int rc = ezmk::workspace_build::run_build(ws, *args.workspace_opts);
            if (rc != 0) return rc;
            break;
        }

        case ezmk::cli::Command::WorkspaceTest: {
            auto ws = require_workspace();
            int rc = ezmk::workspace_build::run_test(ws, *args.workspace_opts);
            if (rc != 0) return rc;
            break;
        }

        case ezmk::cli::Command::WorkspaceClean: {
            auto ws = require_workspace();
            int rc = ezmk::workspace_build::run_clean(ws, *args.workspace_opts);
            if (rc != 0) return rc;
            break;
        }

        case ezmk::cli::Command::Utils: {
            // 1.1.1: intercept `cc` — served by the built-in C++ generator
            // (drift-free compile_commands.json). Other tools keep the Lua path.
            if (args.utils_name == "cc") {
                int rc = run_builtin_cc(args.utils_args);
                if (rc != 0) return rc;
                break;
            }
            // Search for the Lua script across project/user/global scopes
            auto script_path = ezmk::util::find_utils_script(args.utils_name);
            if (script_path.empty()) {
                ezmk::util::fatal(ezmk::i18n::I18nKey::utils_not_found,
                                  {{"name", args.utils_name}});
            }
            int rc = ezmk::lua::run_script(ezmk::lua::state(), script_path,
                                           args.utils_args);
            if (rc != 0) return rc;
            break;
        }

        } // switch

    } catch (const ezmk::fatal_error&) {
        // fatal() already printed the message; just clean up (best-effort)
        // 1.2.0-dev.7: temp dir lives under the located project root
        { std::error_code ec;
          fs::remove_all(ezmk::util::locate_project_root(fs::current_path())
                             .value_or(fs::current_path()) / ".ezmk/temp", ec); }
        ezmk::lua::shutdown();
        return 1;
    } catch (const std::exception& e) {
        ezmk::util::error(e.what());
        // 1.2.0-dev.7: temp dir lives under the located project root
        { std::error_code ec;
          fs::remove_all(ezmk::util::locate_project_root(fs::current_path())
                             .value_or(fs::current_path()) / ".ezmk/temp", ec); }
        ezmk::lua::shutdown();
        return 1;
    }

    ezmk::lua::shutdown();
    return 0;
}
