#include "ezmk/cli.hpp"
#include "ezmk/config.hpp"
#include "ezmk/project.hpp"
#include "ezmk/build.hpp"
#include "ezmk/cache.hpp"
#include "ezmk/pkg.hpp"
#include "ezmk/repo.hpp"
#include "ezmk/util.hpp"
#include "ezmk/i18n.hpp"
#include "ezmk/lua_api.hpp"
#include "ezmk/version.hpp"   // generated by build.sh

#include <exception>
#include <iostream>

int main(int argc, char** argv) {
    ezmk::util::init_console();
    ezmk::i18n::init();  // detect language, load locale data
    ezmk::lua::init();   // initialize Lua interpreter

    try {
        auto args = ezmk::cli::parse(argc, argv);

        switch (args.cmd) {

        case ezmk::cli::Command::Help:
            ezmk::cli::print_usage();
            break;

        case ezmk::cli::Command::ProjectNew:
            ezmk::project::create_project(*args.project_name, args.project_type,
                                          args.disable_git_init, args.disable_gitignore);
            break;

        case ezmk::cli::Command::Version:
            std::cout << ezmk::i18n::fmt(ezmk::i18n::I18nKey::version_output,
                                         {{"version", EZMK_VERSION}}) << std::endl;
            break;

        case ezmk::cli::Command::ProjectBuild: {
            auto cfg = ezmk::config::parse_config("ezmk.toml");
            ezmk::build::build_project(cfg, args.build_opts);
            break;
        }

        case ezmk::cli::Command::ProjectRun: {
            auto cfg = ezmk::config::parse_config("ezmk.toml");
            auto exe = ezmk::build::build_project(cfg, args.build_opts);
            ezmk::util::info(ezmk::i18n::I18nKey::running,
                             {{"exe", exe.filename().string()}});
            auto res = ezmk::util::run_command("\"" + exe.string() + "\"");
            if (!res.out.empty()) std::cout << res.out;
            if (!res.err.empty()) std::cerr << res.err;
            if (res.exit_code != 0) {
                return res.exit_code;
            }
            break;
        }

        case ezmk::cli::Command::ProjectClean:
            ezmk::cache::clear_cache();
            ezmk::util::remove_all(".ezmk/temp");
            ezmk::util::info(ezmk::i18n::I18nKey::cleaned);
            break;

        case ezmk::cli::Command::PkgInstall: {
            auto& opts = *args.install_opts;
            ezmk::pkg::install(opts.pkg_file, opts.scope, opts.sha256, opts.assume_yes);
            break;
        }

        case ezmk::cli::Command::PkgRemove: {
            auto& opts = *args.query_opts;
            ezmk::pkg::remove(opts.pkg_name, opts.scopes);
            break;
        }

        case ezmk::cli::Command::PkgSearch: {
            auto& opts = *args.query_opts;
            auto results = ezmk::pkg::search(opts.pkg_name, opts.scopes);
            if (results.empty()) {
                ezmk::util::info(ezmk::i18n::I18nKey::not_found,
                                 {{"pkg", opts.pkg_name}});
            } else {
                for (auto& p : results) {
                    std::cout << p.string() << "\n";
                }
            }
            break;
        }

        case ezmk::cli::Command::PkgInfo: {
            auto& opts = *args.query_opts;
            ezmk::pkg::info(opts.pkg_name, opts.scopes);
            break;
        }

        case ezmk::cli::Command::RepoAdd:
            ezmk::repo::add(args.repo_opts);
            break;

        case ezmk::cli::Command::RepoRemove:
            ezmk::repo::remove(args.repo_opts.name, args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::RepoUpdate:
            ezmk::repo::update(args.repo_opts.name, args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::RepoList:
            ezmk::repo::list(args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::Utils: {
            // Search for the Lua script across project/user/global scopes
            auto script_path = ezmk::util::find_utils_script(args.utils_name);
            if (script_path.empty()) {
                ezmk::util::fatal(ezmk::i18n::I18nKey::utils_not_found,
                                  {{"name", args.utils_name}});
            }
            int rc = ezmk::lua::run_script(ezmk::lua::state(), script_path,
                                           args.utils_args);
            if (rc != 0) return rc;
            break;
        }

        } // switch

    } catch (const ezmk::fatal_error&) {
        // fatal() already printed the message; just clean up
        ezmk::util::remove_all(".ezmk/temp");
        ezmk::lua::shutdown();
        return 1;
    } catch (const std::exception& e) {
        ezmk::util::error(e.what());
        ezmk::util::remove_all(".ezmk/temp");
        ezmk::lua::shutdown();
        return 1;
    }

    ezmk::lua::shutdown();
    return 0;
}
