#include "ezmk/cli.hpp"
#include "ezmk/config.hpp"
#include "ezmk/project.hpp"
#include "ezmk/build.hpp"
#include "ezmk/cache.hpp"
#include "ezmk/compile_db.hpp"
#include "ezmk/pkg.hpp"
#include "ezmk/repo.hpp"
#include "ezmk/util.hpp"
#include "ezmk/i18n.hpp"
#include "ezmk/lua_api.hpp"
#include "ezmk/file_watcher.hpp"
#include "ezmk/version.hpp"   // generated by build.sh
#include "ezmk/logo.gen.h"     // 0.9.6+: generated by embed_logo.py

#include <atomic>
#include <csignal>
#include <exception>
#include <filesystem>
#include <iostream>
#include <thread>

// 0.2.5+: Auto-update repos helper — shared by build/run/watch commands.
static void auto_update_repos(const ezmk::cli::BuildOptions& opts) {
    if (opts.auto_update) {
        ezmk::util::info(ezmk::i18n::I18nKey::auto_updating_repos);
        ezmk::repo::update("", {ezmk::cli::Scope::Project,
                                 ezmk::cli::Scope::User,
                                 ezmk::cli::Scope::Global});
    }
}

// 1.2.0: shared compile_commands generation entry — used by both the
// `ezmk project cc` command and the (deprecated) `ezmk utils cc` redirect,
// so the two entry points always produce identical output.
static void generate_compile_db_entry(const std::string& output_path,
                                      const std::string& profile) {
    auto cfg = ezmk::config::parse_config("ezmk.toml");
    ezmk::cli::BuildOptions opts;
    opts.profile = profile;
    auto proj_root = std::filesystem::current_path();

    std::filesystem::path out;
    if (!output_path.empty()) {
        out = output_path;
        if (out.is_relative()) out = proj_root / out;
    }

    ezmk::compile_db::generate_compile_db(cfg, opts, proj_root, out);
}

// 1.1.1: Built-in `cc` tool — generates compile_commands.json via the C++
// compile_db generator (drift-free). Intercepts `ezmk utils cc` before the
// Lua script lookup; the Lua cc.lua is no longer executed.
// 1.2.0: `ezmk utils cc` is deprecated — emits a warning, then redirects to
// the shared project-cc entry. The tool stays functional until 2.0.0.
static int run_builtin_cc(const std::vector<std::string>& utils_args) {
    ezmk::util::warn(ezmk::i18n::I18nKey::utils_cc_deprecated);

    std::string output_path;
    std::string profile;
    bool show_help = false;

    for (size_t i = 0; i < utils_args.size(); ++i) {
        const auto& a = utils_args[i];
        if (a == "-h" || a == "--help") {
            show_help = true;
        } else if (a == "-o" || a == "--output") {
            if (i + 1 >= utils_args.size()) {
                ezmk::util::fatal(std::string("option '") + a +
                                  "' for 'ezmk utils cc' requires a value");
            }
            output_path = utils_args[++i];
        } else if (a.rfind("--output=", 0) == 0) {
            output_path = a.substr(9);
        } else if (a == "--profile") {
            if (i + 1 >= utils_args.size()) {
                ezmk::util::fatal(std::string("option '") + a +
                                  "' for 'ezmk utils cc' requires a value");
            }
            profile = utils_args[++i];
        } else if (a.rfind("--profile=", 0) == 0) {
            profile = a.substr(10);
        } else {
            ezmk::util::fatal(std::string("unknown option for 'ezmk utils cc': ") + a);
        }
    }

    if (show_help) {
        std::cout << ezmk::i18n::get(ezmk::i18n::I18nKey::cc_help) << "\n";
        return 0;
    }

    generate_compile_db_entry(output_path, profile);
    return 0;
}

namespace fs = std::filesystem;

int main(int argc, char** argv) {
    ezmk::util::init_console();
    ezmk::i18n::init();  // detect language, load locale data
    ezmk::lua::init();   // initialize Lua interpreter

    try {
        auto args = ezmk::cli::parse(argc, argv);

        // 0.9.8+: show shorthand expansion hint in verbose mode
        if (!args.shorthand_expansion.empty()) {
            ezmk::util::info_line(ezmk::i18n::fmt(ezmk::i18n::I18nKey::shorthand_expansion,
                                                  {{"mapping", args.shorthand_expansion}}));
        }

        switch (args.cmd) {

        case ezmk::cli::Command::Help: {
            // 0.9.6+: Show ASCII logo (with color when available)
            if (ezmk::EZMK_LOGO[0] != '\0') {
                bool use_color = ezmk::util::supports_color();
                if (use_color) {
                    std::cout << "\033[36m" << ezmk::EZMK_LOGO << "\033[0m\n";
                } else {
                    std::cout << ezmk::EZMK_LOGO << "\n";
                }
                // Show version below logo
                std::cout << ezmk::i18n::fmt(ezmk::i18n::I18nKey::version_output,
                                             {{"version", EZMK_VERSION}}) << "\n\n";
            }
            ezmk::cli::print_usage();
            break;
        }

        case ezmk::cli::Command::ProjectNew:
            ezmk::project::create_project(*args.project_name, args.project_type,
                                          args.disable_git_init, args.disable_gitignore);
            break;

        case ezmk::cli::Command::Version:
            std::cout << ezmk::i18n::fmt(ezmk::i18n::I18nKey::version_output,
                                         {{"version", EZMK_VERSION}}) << std::endl;
            break;

        case ezmk::cli::Command::ProjectBuild: {
            auto_update_repos(args.build_opts);
            auto cfg = ezmk::config::parse_config("ezmk.toml");
            ezmk::build::build_project(cfg, args.build_opts);
            break;
        }

        case ezmk::cli::Command::ProjectRun: {
            auto_update_repos(args.build_opts);
            auto cfg = ezmk::config::parse_config("ezmk.toml");
            auto exe = ezmk::build::build_project(cfg, args.build_opts);
            ezmk::util::info(ezmk::i18n::I18nKey::running,
                             {{"exe", exe.filename().string()}});
            // 0.2.5+: forward positional args (after "--") to the program.
            std::string cmd = "\"" + exe.string() + "\"";
            for (const auto& a : args.program_args) {
                cmd += " \"" + ezmk::util::escape_shell_arg(a) + "\"";
            }
            auto res = ezmk::util::run_command(cmd);
            if (!res.out.empty()) std::cout << res.out;
            if (!res.err.empty()) std::cerr << res.err;
            if (res.exit_code != 0) {
                return res.exit_code;
            }
            break;
        }

        case ezmk::cli::Command::ProjectClean:
            ezmk::cache::clear_cache();
            { std::error_code ec; fs::remove_all(".ezmk/temp", ec); }  // best-effort
            ezmk::util::info(ezmk::i18n::I18nKey::cleaned);
            break;

        // 1.1.0: project install
        case ezmk::cli::Command::ProjectInstall: {
            auto cfg = ezmk::config::parse_config("ezmk.toml");
            auto proj_root = std::filesystem::current_path();

            // Build first
            ezmk::build::build_project(cfg, args.build_opts);

            // Install
            ezmk::build::install_project(cfg, args.project_install_opts, proj_root);
            break;
        }

        case ezmk::cli::Command::ProjectPack: {
            auto cfg = ezmk::config::parse_config("ezmk.toml");
            auto proj_root = std::filesystem::current_path();

            ezmk::build::pack_project(cfg, *args.project_pack_opts, proj_root);
            break;
        }

        // 1.2.0: project cc — formal compile_commands generation command
        case ezmk::cli::Command::ProjectCc: {
            const auto& opts = *args.project_cc_opts;
            generate_compile_db_entry(opts.output, opts.profile);
            break;
        }

        // 1.1.0-dev.6: project test
        case ezmk::cli::Command::ProjectTest: {
            auto_update_repos(args.build_opts);
            auto cfg = ezmk::config::parse_config("ezmk.toml");
            ezmk::build::run_tests(cfg,
                                    args.test_framework,
                                    args.test_filter,
                                    args.test_verbose);
            break;
        }

        case ezmk::cli::Command::ProjectWatch: {
            // 0.2.3+: Watch mode — file monitoring + auto rebuild
            auto_update_repos(args.build_opts);
            auto cfg = ezmk::config::parse_config("ezmk.toml");
            auto proj_root = std::filesystem::current_path();

            // Build effective config (profile merge)
            ezmk::config::CompileSection compile_cfg = cfg.compile;
            ezmk::config::LinkSection link_cfg = cfg.link;
            if (!args.build_opts.profile.empty()) {
                auto it = cfg.compile_profiles.find(args.build_opts.profile);
                if (it != cfg.compile_profiles.end()) {
                    compile_cfg = ezmk::build::merge_compile_profile(compile_cfg, it->second);
                }
                auto lit = cfg.link_profiles.find(args.build_opts.profile);
                if (lit != cfg.link_profiles.end()) {
                    link_cfg = ezmk::build::merge_link_profile(link_cfg, lit->second);
                }
            }

            // SIGINT handler for graceful exit
            static std::atomic<bool> sigint_received{false};
            auto prev_handler = std::signal(SIGINT, [](int) {
                sigint_received = true;
            });

            // Initial build (unless --no-build-on-start)
            if (!args.watch_no_build_on_start) {
                try {
                    ezmk::build::build_project(cfg, args.build_opts);
                    ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                } catch (const std::exception& e) {
                    ezmk::util::error(std::string("initial build failed: ") + e.what());
                    ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                }
            } else {
                ezmk::util::info(ezmk::i18n::I18nKey::watch_skip_initial);
            }

            // Collect directories to watch
            std::vector<std::string> watch_dirs;
            // Use absolute path to ezmk.toml so parent_path() resolves correctly
            watch_dirs.push_back((proj_root / "ezmk.toml").string());
            for (auto& d : compile_cfg.src_dirs) {
                std::filesystem::path dir = d;
                if (dir.is_relative()) dir = proj_root / dir;
                if (std::filesystem::exists(dir)) watch_dirs.push_back(dir.string());
            }
            for (auto& d : compile_cfg.include_dirs) {
                std::filesystem::path dir = d;
                if (dir.is_relative()) dir = proj_root / dir;
                if (std::filesystem::exists(dir)) watch_dirs.push_back(dir.string());
            }

            // Create file watcher
            auto ezmk_toml_abs = std::filesystem::absolute(proj_root / "ezmk.toml").string();
            ezmk::util::FileWatcher watcher(
                [&](const std::filesystem::path& changed) {
                    auto changed_abs = std::filesystem::absolute(changed).string();
                    auto changed_name = changed.filename().string();

                    // Check if ezmk.toml changed → re-parse config, clear cache, full rebuild
                    if (changed_abs == ezmk_toml_abs || changed_name == "ezmk.toml") {
                        ezmk::util::info(ezmk::i18n::I18nKey::watch_config_changed);
                        ezmk::cache::clear_cache();
                        try {
                            auto new_cfg = ezmk::config::parse_config("ezmk.toml");
                            ezmk::build::build_project(new_cfg, args.build_opts);
                            ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                        } catch (const std::exception& e) {
                            ezmk::util::error(std::string("build failed: ") + e.what());
                            ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                        }
                        return;
                    }

                    // Source/header change → incremental build
                    ezmk::util::info(ezmk::i18n::I18nKey::watch_detected_change,
                                     {{"path", changed_abs}});
                    try {
                        auto cur_cfg = ezmk::config::parse_config("ezmk.toml");
                        ezmk::build::build_project(cur_cfg, args.build_opts);
                        ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                    } catch (const std::exception& e) {
                        ezmk::util::error(std::string("build failed: ") + e.what());
                        ezmk::util::info(ezmk::i18n::I18nKey::watch_started);
                    }
                },
                300  // 300ms debounce
            );

            // Add directories to watcher
            for (auto& d : watch_dirs) {
                std::filesystem::path dp(d);
                if (dp.filename() == "ezmk.toml") {
                    // Watch the parent directory of ezmk.toml non-recursively
                    watcher.add_directory(dp.parent_path(), /*recursive=*/false);
                } else {
                    watcher.add_directory(dp, /*recursive=*/true);
                }
            }

            // Run watcher in background thread, main thread waits for SIGINT
            std::thread watcher_thread([&watcher]() {
                watcher.run();
            });

            // Wait for SIGINT
            while (!sigint_received) {
                std::this_thread::sleep_for(std::chrono::milliseconds(200));
            }

            ezmk::util::info(ezmk::i18n::I18nKey::watch_stopping);
            watcher.stop();
            if (watcher_thread.joinable()) watcher_thread.join();

            // Restore previous handler
            std::signal(SIGINT, prev_handler);
            break;
        }

        case ezmk::cli::Command::PkgInstall: {
            auto& opts = *args.install_opts;
            ezmk::pkg::install(opts.pkg_file, opts.scope, opts.sha256, opts.assume_yes,
                                opts.locked, opts.no_lock);
            break;
        }

        case ezmk::cli::Command::PkgRemove: {
            auto& opts = *args.query_opts;
            ezmk::pkg::remove(opts.pkg_name, opts.scopes);
            break;
        }

        case ezmk::cli::Command::PkgSearch: {
            auto& opts = *args.query_opts;
            auto results = ezmk::pkg::search(opts.pkg_name, opts.scopes);
            if (results.empty()) {
                ezmk::util::info(ezmk::i18n::I18nKey::not_found,
                                 {{"pkg", opts.pkg_name}});
            } else {
                for (auto& p : results) {
                    std::cout << p.string() << "\n";
                }
            }
            break;
        }

        case ezmk::cli::Command::PkgInfo: {
            auto& opts = *args.query_opts;
            ezmk::pkg::info(opts.pkg_name, opts.scopes);
            break;
        }

        case ezmk::cli::Command::PkgList: {
            // 0.2.3+ — implementation in Phase 5
            auto& opts = *args.query_opts;
            ezmk::pkg::list(opts.scopes);
            break;
        }

        case ezmk::cli::Command::PkgUpdate: {
            auto& opts = *args.query_opts;
            if (opts.update_all) {
                ezmk::pkg::update_all(opts.scopes);
            } else {
                ezmk::pkg::update(opts.pkg_name, opts.scopes);
            }
            break;
        }

        case ezmk::cli::Command::RepoAdd:
            ezmk::repo::add(args.repo_opts);
            break;

        case ezmk::cli::Command::RepoRemove:
            ezmk::repo::remove(args.repo_opts.name, args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::RepoUpdate:
            ezmk::repo::update(args.repo_opts.name, args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::RepoList:
            ezmk::repo::list(args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::RepoInfo:   // 0.2.5+
            ezmk::repo::info(args.repo_opts.name, args.repo_opts.scopes);
            break;

        case ezmk::cli::Command::Utils: {
            // 1.1.1: intercept `cc` — served by the built-in C++ generator
            // (drift-free compile_commands.json). Other tools keep the Lua path.
            if (args.utils_name == "cc") {
                int rc = run_builtin_cc(args.utils_args);
                if (rc != 0) return rc;
                break;
            }
            // Search for the Lua script across project/user/global scopes
            auto script_path = ezmk::util::find_utils_script(args.utils_name);
            if (script_path.empty()) {
                ezmk::util::fatal(ezmk::i18n::I18nKey::utils_not_found,
                                  {{"name", args.utils_name}});
            }
            int rc = ezmk::lua::run_script(ezmk::lua::state(), script_path,
                                           args.utils_args);
            if (rc != 0) return rc;
            break;
        }

        } // switch

    } catch (const ezmk::fatal_error&) {
        // fatal() already printed the message; just clean up (best-effort)
        { std::error_code ec; fs::remove_all(".ezmk/temp", ec); }
        ezmk::lua::shutdown();
        return 1;
    } catch (const std::exception& e) {
        ezmk::util::error(e.what());
        { std::error_code ec; fs::remove_all(".ezmk/temp", ec); }
        ezmk::lua::shutdown();
        return 1;
    }

    ezmk::lua::shutdown();
    return 0;
}
