-- ezmk-official-utils: gen-build-package — build package generator
--
-- Generates a self-contained build package (.tar.gz) from the current project.
-- The package includes all source files, headers, ezmk.toml, and a generated
-- build script so the project can be built on any machine with ezmk installed.
--
-- Usage:
--   ezmk utils gen-build-package [--output <dir>] [--name <name>]

function help()
    return [[
usage: ezmk utils gen-build-package [options]

Generate a self-contained build package (.tar.gz) for the current project.

The package includes:
  - All source files from configured source directories
  - All header files from configured include directories
  - The project ezmk.toml
  - A generated build script (build.sh + build.ps1)

Options:
  -o, --output  <dir>    Output directory (default: current directory)
  -n, --name    <name>   Package name (default: <project_name>-build)
  -h, --help             Show this help

Examples:
  ezmk utils gen-build-package
  ezmk utils gen-build-package -o ../dist -n myapp-v1.0
]]
end

-- Create a directory if it doesn't exist
local function ensure_dir(path)
    -- Use ezmk's file system API to write a temp file and remove it
    -- to ensure the parent directory exists
    -- Actually, we rely on the build script creating directories as needed
end

function run(args)
    local output_dir = "."
    local pkg_name = nil
    local i = 1
    while i <= #args do
        local a = args[i]
        if a == "-o" or a == "--output" then
            i = i + 1
            if i <= #args then
                output_dir = args[i]
            else
                error("-o/--output requires a path argument")
            end
        elseif a == "-n" or a == "--name" then
            i = i + 1
            if i <= #args then
                pkg_name = args[i]
            else
                error("-n/--name requires a name argument")
            end
        elseif a == "-h" or a == "--help" then
            print(help())
            return 0
        end
        i = i + 1
    end

    local root = ezmk.project_root()
    local project_name = ezmk.project_name()
    local project_version = ezmk.project_version()

    if not pkg_name then
        pkg_name = project_name .. "-build-" .. (project_version or "0.1.0")
    end

    if output_dir:sub(1, 1) ~= "/" and output_dir:sub(2, 2) ~= ":" then
        output_dir = root .. "/" .. output_dir
    end

    -- Create staging directory
    local stage = output_dir .. "/" .. pkg_name
    ezmk.info("Generating build package: " .. pkg_name)

    -- Determine source and include directories
    local src_dirs = ezmk.source_dirs()
    if type(src_dirs) ~= "table" or #src_dirs == 0 then
        src_dirs = {"src"}
    end
    local include_dirs = ezmk.include_dirs()
    if type(include_dirs) ~= "table" or #include_dirs == 0 then
        include_dirs = {"include"}
    end

    -- Collect file list
    local files_to_copy = {}

    -- ezmk.toml
    files_to_copy[#files_to_copy + 1] = "ezmk.toml"

    -- Source files
    for _, dir in ipairs(src_dirs) do
        local full = root .. "/" .. dir
        local sources = ezmk.list_sources()
        for _, src in ipairs(sources) do
            -- Check if this source is under this src_dir
            local rel = src
            if rel:sub(1, #root) == root then
                rel = rel:sub(#root + 2)
            end
            if rel:sub(1, 1) == "/" then
                rel = rel:sub(2)
            end
            -- Include if under the src_dir or no dir filtering needed
            files_to_copy[#files_to_copy + 1] = rel
        end
    end

    -- Header files (if different from src)
    for _, dir in ipairs(include_dirs) do
        local full = root .. "/" .. dir
        if ezmk.file_exists(full) then
            files_to_copy[#files_to_copy + 1] = dir .. "/"
        end
    end

    -- Generate build scripts
    local build_sh = [=[
#!/usr/bin/env bash
# Auto-generated by: ezmk utils gen-build-package
# Project: ]=] .. project_name .. [=[ (]=] .. (project_version or "0.0.0") .. [=[)
set -euo pipefail
cd "$(dirname "$0")"
echo "Building ]=] .. project_name .. [=[..."
ezmk project build
echo "Build complete."
]=]

    local build_ps1 = [=[
# Auto-generated by: ezmk utils gen-build-package
# Project: ]=] .. project_name .. [=[ (]=] .. (project_version or "0.0.0") .. [=[)
$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot
Write-Host "Building ]=] .. project_name .. [=[..."
ezmk project build
Write-Host "Build complete."
]=]

    -- Write files to staging area
    -- We use ezmk.run_command to create the directory
    local function shell_escape(s)
        -- Basic shell escaping for paths
        return '"' .. s:gsub('"', '\\"') .. '"'
    end

    local escaped_stage = shell_escape(stage)

    -- Create staging directory
    local rc = ezmk.run_command("mkdir -p " .. escaped_stage)
    if rc ~= 0 then
        -- Try Windows mkdir
        rc = ezmk.run_command("mkdir " .. escaped_stage .. " 2>nul")
    end

    -- Copy files using run_command (cp / xcopy)
    local is_windows = (ezmk.platform() or ""):find("win")
    local copy_cmd = is_windows and "xcopy /E /I /Y" or "cp -r"

    -- Copy ezmk.toml
    local src = root .. "/ezmk.toml"
    if ezmk.file_exists(src) then
        ezmk.run_command(copy_cmd .. " " .. shell_escape(src) .. " " .. escaped_stage .. "/")
    end

    -- Copy source directories
    local dedup = {}
    for _, dir in ipairs(src_dirs) do
        if not dedup[dir] then
            dedup[dir] = true
            local full = root .. "/" .. dir
            if ezmk.file_exists(full) then
                ezmk.run_command(copy_cmd .. " " .. shell_escape(full) .. " " .. escaped_stage .. "/" .. dir .. "/")
            end
        end
    end

    -- Copy include directories
    for _, dir in ipairs(include_dirs) do
        if not dedup[dir] then
            dedup[dir] = true
            local full = root .. "/" .. dir
            if ezmk.file_exists(full) then
                ezmk.run_command(copy_cmd .. " " .. shell_escape(full) .. " " .. escaped_stage .. "/" .. dir .. "/")
            end
        end
    end

    -- Write build scripts
    local ok_sh, err_sh = ezmk.file_write(stage .. "/build.sh", build_sh)
    if ok_sh then
        ezmk.run_command("chmod +x " .. shell_escape(stage .. "/build.sh"))
    end
    ezmk.file_write(stage .. "/build.ps1", build_ps1)

    -- Create tar.gz archive
    local archive = output_dir .. "/" .. pkg_name .. ".tar.gz"
    local cwd = ezmk.run_command("cd " .. shell_escape(output_dir) .. " && tar -czf " .. shell_escape(archive) .. " " .. shell_escape(pkg_name))

    -- Cleanup staging
    ezmk.run_command((is_windows and "rmdir /S /Q " or "rm -rf ") .. escaped_stage)

    if ezmk.file_exists(archive) then
        ezmk.info("Build package generated: " .. archive)
        return 0
    else
        -- Fallback: keep staging directory if tar failed
        ezmk.warn("tar command failed, staging directory kept at: " .. stage)
        return 1
    end
end
